### PR TITLE
Add example local.conf for creating a USB recovery drive using a Samba share

### PR DESCRIPTION
**Pull request by danboid**
Add example local.conf for creating a USB recovery drive using a Samba share

### CODE REVIEW

**Comment by jsmeix** [comment]
@danboid 
please replace the real device node in
<pre>
# Be sure to set the device correctly!
USB_DEVICE=/dev/sdb1
</pre>
with a safe device node template like
<pre>
# Specify your actually right device node (e.g. /dev/sdb1)
USB_DEVICE=/dev/sdXN
</pre>

**Comment by danboid** [comment]
Thanks for your feedback jsmeix and gdha! I have adopted your suggestions and pushed a new version of the example config.

**Comment by jsmeix** [comment]
@danboid 
I merged it.

**Comment by danboid** [comment]
Great - thanks jsmeix!

**Pull request merged**
