### PR TITLE
add custom script support besides PRE_RECOVERY_SCRIPT and PORT_RECOVERY_...

### PR DESCRIPTION
**Pull request by tbsky**
hi:
   this is a patch for adding custom script support. this feature works like PRE_RECOVERY_SCRIPT and POST_RECOVERY_SCRIPT , but add that ability to other stages by hooking every script at all stages. definition at config file like below:

PRE_BACKUP_97_SCRIPT=(/usr/local/bin/rear-drbd_vm_backup)
POST_RESTORE_98_SCRIPT=(/usr/local/bin/rear-drbd_vm_restore)

  the patch is made by suggestion/hint from schlomo:

1. working at function "Source", not "SourceStage". but I did change one line at  fucntion "SourceStage". this can be prevented by add more lines at function "Source", so it is a coding choice. I found function "Source" seems only be called by "SourceStage", but maybe that is just a coincidence. please comment which coding style is preferred.

2. the format of script name is "PRE_$stage_$priority_SCRIPT" and "POST_$stage_$priority_SCRIPT"

3. the processing of script is the same as  PRE_RECOVERY_SCRIPT and  POST_RECOVERY_SCRIPT.

### CODE REVIEW

**Comment by gdha** [comment]
Don't think we better post-pone this to next release rear-1.18

**Comment by schlomo** [comment]
Well, why not simply add `"$CONFIG_DIR/workflow/$stage"/*.sh` as described above and add a deprecation warning to the POST_* and PRE_* script variables?

@gdha, @dagwieers, @jhoekx please tell me what you think about this approach?

**Comment by gdha** [comment]
@schlomo I don't mind as long everybody agrees on the way forward. So +1

**Comment by pavoldomin** [comment]
Hi, looks fine to me. But, if I get it right, the suggestion:
```
   scripts=(
   ...
        ls -d   
            "$CONFIG_DIR/workflow/$stage"/*.sh \
        ...
```
means, we add our custom scripts to the ones shipped by ReaR. It is not exactly what @tbsky originally aimed for I think: we call our workflow scripts **added** to the ReaR ones, but would be more flexible if we **replace** the ReaR script with our one, if the script with same name exists in ReaR's own workflow path.

But perhaps I speculate too much here.

**Comment by schlomo** [comment]
I see what you mean.

Do we now have an actual requirement to *overlay* ReaR scripts?

@tbsky, can you please let us know if *adding* scripts would be enough for
your current need.

IMHO adding the option to overlay or disable ReaR scripts is a very
dangerous feature as many scripts depend on each other. If users need to be
able to disable some feature or behaviour then we should include variables
for that.

**Comment by tbsky** [comment]
@schlomo 

    I think it is good to separate rear official scripts and custom scripts. for me need, I already use rpm to deploy custom scripts to call my custom functions, so I can  manage all the configurations in one config file.  that's enough for me.

**Comment by schlomo** [comment]
@tbsky, does that mean that we can close this issue and do nothing?

Or would it help you if I implement the addition I suggested above?

**Comment by tbsky** [comment]
@schlomo
      
       yes we can close it since it is not really a problem, just an enhancement. but as you said, I think implement  a infrastructure for user-defined custom scripts  is a good thing.

**Comment by gdha** [comment]
@schlomo Shall we silently close this pull request as there is no general demand for it. Rear is more then complex enough.

**Comment by schlomo** [comment]
@gdha yes, in favour. I prefer users to plug scripts into the ReaR tree and I would ask them to accept that this is how we want them to extend ReaR.

**Comment by jsmeix** [comment]
A note only FYI:

I appreciate everything that reduces complexity in Rear.

Keep It Simple and Straightforward cf. RFC 1925 (6a)
and
Keep Separated Issues Separated cf. RFC 1925 (5)

**Pull request closed without merging**
