### PR TITLE
#3067 use exit code of nc to check BACULA directory availability

### PR DESCRIPTION
**Pull request by gdha**
#### Relax-and-Recover (ReaR) Pull Request Template

Please fill in the following items before submitting a new pull request:

##### Pull Request Details:

* Type: **Bug Fix**

* Impact: **Normal**

* Reference to related issue (URL):
#3067 
#3082

* How was this pull request tested? Not yet - requested it via issue #3067 

* Description of the changes in this pull request:
`ERROR: Bacula director debian11-DR6 is not responding` - purpose is to have a simple test to verify to Bacula connector is responsive or not.

### CODE REVIEW

**Comment by gdha** [comment]
@rear/contributors what shall we do with this PR? Merge or drop?

**Review by jsmeix — APPROVED** [review]
I cannot actually review it
because I do not have BACULA
but from plain looking at the code changes
I don't see something obviously wrong
so I approve it "bona fide"

**Comment by jsmeix** [comment]
I think we should merge it
regardless that the users who had the issues do not respond
because the changes intend to improve things.
I.e. I think better try to improve things than do nothing.

**Comment by gdha** [comment]
This PR may fix issues #3067 and #3082 - we will see what the future brings...

**Pull request merged**
