### PR TITLE
exclude multipath device that does not have mounted fs

### PR DESCRIPTION
**Pull request by schabrolles**
#### Relax-and-Recover (ReaR) Pull Request Template

Please fill in the following items before submitting a new pull request:

##### Pull Request Details:

* Type: **Bug Fix**

* Impact: **Normal**

* Reference to related issue (URL):
https://github.com/rear/rear/issues/1767

* How was this pull request tested?
SLES12SP2 on POWER with multipath devices

* Brief description of the changes in this pull request:
The actual code without this patch just exclude "real disk" which doesn't have fs mounted, not mutlipath devices.
This path check if fs has parent device in disk AND multipath, then exclude disk and multipath with no fs mounted.

### CODE REVIEW

**Comment by jsmeix** [comment]
@schabrolles 
please add explanatory comments why "multipath" is also there
so that others at any later time (who may have nothing to do with "multipath")
immediately understand how "multipath" also belongs there.

Only optionally:
Could you perhaps "by the way" also clean up code like
<pre>
if [[ "$AUTOEXCLUDE_..." =~ ^[yY1] ]] ; then
</pre>
to the current way like
<pre>
if is_true "$AUTOEXCLUDE_..." ; then
</pre>

**Comment by jsmeix** [comment]
Meanwhile I may no longer understand how that autoexlude code is meant in general,
see https://github.com/rear/rear/issues/1767#issuecomment-387685874

**Comment by jsmeix** [comment]
After looking a bit closer I think meanwhile I do again understand it
and this is what I currently think how that autoexlude code is meant:

When AUTOEXCLUDE_DISKS is true
it collects in the used_disks array
all disks that ars somehow used
for swap
and/or by a mounted filesystem
and then it automatically excluded only those disks
that are not in the used_disks array.

This means a disk that has partitions
for supported and mounted filesystems
plus partitions for unsupported filesystems
will not be automatically excluded
when at least one of its partitions is used
(as swap or by a mounted filesystem).

Your change enhances that by also
automatically exclude multipath devices
when none of its partitions is used
(as swap or by a mounted filesystem).

If my current understanding is actually right,
your changes look perfectly right to me.

**Comment by schabrolles** [comment]
Last changes ... Add comments and also replace `find_disk` by `find_disk_and_multiapth` function during swap parent device detection.

**Pull request merged**
