### PR TITLE
Borg as back end, now accepts options for repository encryption (take 2)

### PR DESCRIPTION
**Pull request by gozora**
- borg as back end, now accepts options for repository encryption.
- prune now only affects archives with BORGBACKUP_ARCHIVE_PREFIX

### CODE REVIEW

**Comment by gozora** [comment]
@jsmeix 
Hope this one is better.

**Comment by gozora** [comment]
Today I've discovered some useful Borg environment variables, that allows automatic launch of backup to encrypted repository (sending pass-phrases from ReaR to Borg in non-interactive session should not be a problem any longer).
I'll prepare pull request with this enhancement.

Btw. Do we have some preferred way of storing sensitive information like passwords?

V.

**Comment by jsmeix** [comment]
@gozora 
off the top of my head I don't know a preferred way of
storing sensitive information like passwords.
For example I implemented an optional password
for ftpfs, see https://github.com/rear/rear/issues/845
and https://github.com/rear/rear/pull/859
where the password either must be manually entered
several times during "rear mkbackup" and "rear recover"
see https://github.com/rear/rear/pull/859#issuecomment-223540169
but this way it is the secure method or alternatively
the password can be (optionally) specified as plain text
in the BACKUP_URL variable and then it is up to
the user how to protect that info in /etc/rear/local.conf

**Comment by gozora** [comment]
@jsmeix,
Thanks, I'll check that!

**Pull request merged**
