### PR TITLE
unnessary cat command removed

### PR DESCRIPTION
**Pull request by ProBackup-nl**
PROCS and SPEED made more alike memory_in_kB assignment

### CODE REVIEW

**Comment by ProBackup-nl** [comment]
Maybe core counting can even be reduced to the shorter `grep -c 'core id' /proc/cpuinfo`

**Comment by ProBackup-nl** [comment]
And the actual running speed is not that interesting:

> 567.873

The actual maximum rate is. Better store the model name:

> Intel(R) Atom(TM) CPU  E3815  @ 1.46GHz

**Comment by gdha** [comment]
@ProBackup-nl You may modify the script to improve it further from my point of view. Thank you for the updates already

**Comment by ProBackup-nl** [comment]
Regarding memory, of which interest would be the output of:
```
$ dmidecode -qt 17
Memory Device
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 8192 MB
	Form Factor: SODIMM
	Set: None
	Locator: SODIMM0
	Bank Locator: Channel A Slot 0
	Type: DDR3
	Type Detail: Unknown
	Speed: 1600 MT/s
	Manufacturer: Kingston
	Serial Number: 0B1CABBC
	Asset Tag: A1_AssetTagNum0
	Part Number: 99U5428-018.A00LF
	Rank: 2
	Configured Clock Speed: 1066 MT/s
	Minimum Voltage: 1.35 V
	Maximum Voltage: 1.5 V
	Configured Voltage: 1.35 V
```

**Comment by gdha** [comment]
@ProBackup-nl `dmicode` may be used, if the command is available, to show additional information

**Comment by schabrolles** [comment]
@gdha, @ProBackup-nl, Try to avoid using `dmidecode` when possible as it exists only for x86 arch.

**Pull request merged**
