### PR TITLE
Fixed, simplified and enhanced GRUB2 installation

### PR DESCRIPTION
**Pull request by jsmeix**
Fixed, simplified and enhanced GRUB2 installation
plus fixed typos 'whereto' -> 'where to'

* Type: **Bug Fix** and **Enhancement**

* Impact: **High**

* Reference to related issue (URL):
https://github.com/rear/rear/issues/1828

* How was this pull request tested?
Currently tested only on SLES12 to keep backward compatibility
(as far as I can test it with reasonable effort for me).
I need to also test it on SLES15 (tomorrow).

* Brief description of the changes in this pull request:

Fixed finalize/Linux-i386/620_install_grub2.sh according to
https://github.com/rear/rear/issues/1828#issuecomment-398717889

Enhanced GRUB2 installation by the new config variable
GRUB2_INSTALL_DEVICES so that now the user can specify
what he wants if needed.

Cleaned up finalize/Linux-i386/620_install_grub2.sh
from old inconsistent and even contradictory looking code.

### CODE REVIEW

**Comment by jsmeix** [comment]
With the current state things do "just work" for me also on SLES15.

**Comment by jsmeix** [comment]
With the current state things work much safer for me on SLES12.
SLES15 will be tested tomorrow.

I am still not fully satisfied how finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
behaves (e.g. it replaces disks like `sda => sdb` also in comments) but for now
its changes are no longer possibly fatal for the user because since
https://github.com/rear/rear/pull/1843/commits/632bc2dee4d5b82cfe91416c81254f0bc9919a70
now behaves safer because the original restored files get saved before they get modified.

**Comment by jsmeix** [comment]
In finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
I will add the inexplicably missing `popd` at the end because
I cannot see a reason why it is not there in this particular script
but all other `finalize` scripts have paired `pushd` and `popd`:
<pre>
# for f in $( usr/sbin/rear -s recover | grep -o 'finalize/.*' ) ; do f=usr/share/rear/$f ; echo $f ; egrep '^pushd|^popd' $f ; done

usr/share/rear/finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
pushd $TARGET_FS_ROOT >/dev/null

usr/share/rear/finalize/GNU/Linux/250_migrate_lun_wwid.sh
pushd $TARGET_FS_ROOT >&2
popd >&2 

usr/share/rear/finalize/GNU/Linux/280_migrate_uuid_tags.sh
pushd $TARGET_FS_ROOT >/dev/null
popd >/dev/null
</pre>

**Comment by gdha** [comment]
A recent test ( https://github.com/gdha/rear-automated-testing/issues/65 ) revealed that the new code fails on centos/7

**Pull request merged**
