### PR TITLE
Simplify case insensitive /boot/efi match in 320_include_uefi_env

### PR DESCRIPTION
**Pull request by ProBackup-nl**
(2) Also trying to fix:

> FIXME: I <jsmeix@suse.de> wonder if ReaR should also decide via the code below
> if the variable USING_UEFI_BOOTLOADER has already an explicit 'true' value set.
> I think if the variable USING_UEFI_BOOTLOADER has an explicit 'true' value set
> but the code below returns before "it is safe to turn on USING_UEFI_BOOTLOADER=1"
> then something is probably wrong because the user wants USING_UEFI_BOOTLOADER
> but the tests in the code below seem to contradict what the user wants
> so that probably ReaR should better abort here with an error and not
> blindly proceed and then fail later in arbitrary unpredictable ways
> cf. https://github.com/rear/rear/issues/801#issuecomment-200353337
> or is it also usually "safe to proceed with USING_UEFI_BOOTLOADER=1"
> when the user has explicitly specified that regardless of the tests below?

(3) Inserting FIXME for the potential redundant /boot/[eE][fF][iI] check.

### CODE REVIEW

**Comment by jsmeix** [comment]
@gdha 
can you have a look at the code below
<pre>
# next step, is case-sensitive checking /boot for case-insensitive /efi directory (we need it)
# FIXME: I <2010@probackup.nl> wonder whether it is necessary to have this check here because
# an identical check is already there in 310_include_uefi_tools.sh 
# and the next step "check filesystem partition type (vfat?)" has near identical logic.
</pre>
because according to
"git log -p --follow  usr/share/rear/prep/default/320_include_uefi_env.sh"
that test was initially from you.

**Comment by gdha** [comment]
@jsmeix @ProBackup-nl @gozora  `usr/share/rear/prep/default/320_include_uefi_env.sh` needs a serious facelift - will have a look at it during this week if time permits

**Comment by gozora** [comment]
This PR is superseded by https://github.com/rear/rear/pull/1481, hence can be closed.
Any objections?

V.

**Comment by jsmeix** [comment]
Superseded by https://github.com/rear/rear/pull/1481

**Pull request closed without merging**
