### PR TITLE
small fix to the 58-start-dhclient.sh script

### PR DESCRIPTION
**Pull request by gdha**
Signed-off-by: Gratien D'haese <gratien.dhaese@gmail.com>

##### Pull Request Details: small fix to the 58-start-dhclient.sh script

* Type: **Bug Fix**

* Impact: **Low**

* Reference to related issue (URL): #1274 

* How was this pull request tested? not tested yet

* Brief description of the changes in this pull request: with multiple lan interface it might fail to acquire an IP address, with this little fix it should work.

### CODE REVIEW

**Comment by gerhard-tinned** [comment]
Would love to get this fix ... I ran exactly into this problem.

**Comment by jsmeix** [comment]
I am not at all a DHCP expert but by plain looking at the code I wonder
why not the same fix is also needed for the `IPv6 DHCP clients` case in
usr/share/rear/skel/default/etc/scripts/system-setup.d/58-start-dhclient.sh

**Comment by jsmeix** [comment]
@gdha 
if that fix is really only needed for the IPv4 case but not for the IPv6 case
could you then please add a comment at that code that explains why
both cases are different, cf. "Code should be easy to understand" at
https://github.com/rear/rear/wiki/Coding-Style

**Comment by gdha** [comment]
@jsmeix sharp remark Johannes and right as usual :+1:  fixed it too now

**Pull request merged**
