### PR TITLE
systemd-boot support added

### PR DESCRIPTION
**Pull request by ProBackup-nl**
https://github.com/rear/rear/issues/1214

### CODE REVIEW

**Comment by ProBackup-nl** [comment]
I have no experience with `mkbackup`.

Should that do the `mkrescue` step again? Or not?

like:
```
$ usr/sbin/rear -v mkbackup
Relax-and-Recover 2.00 / Git
Using log file: /root/rear/var/log/rear/rear-d2.log
Using backup archive '/tmp/rear.kFTJoyf1ski6Bj4/outputfs/rear/d2/20170320.2015/backup'
/boot/EFI directory found
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Creating disk layout
Creating root filesystem layout
Trying to find what to use as UEFI bootloader...
Trying to find a 'well known file' to be used as UEFI bootloader...
Using '/boot/EFI/systemd/systemd-bootx64.efi' as UEFI bootloader file
Copying logfile /root/rear/var/log/rear/rear-d2.log into initramfs as '/tmp/rear-d2-partial-2017-03-20T20:15:44+01:00.log'
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Creating recovery/rescue system initramfs/initrd initrd.lz4 with lz4 compression
Created initrd.lz4 with lz4 compression (73546480 bytes) in 5 seconds
'/boot/EFI/systemd/systemd-bootx64.efi' -> '/tmp/rear-efi.WLuiY//EFI/BOOT/BOOTX64.efi'
Copying resulting files to usb location
Saving /root/rear/var/log/rear/rear-d2.log as rear-d2.log to usb location
Creating rsync archive '/tmp/rear.kFTJoyf1ski6Bj4/outputfs/rear/d2/20170320.2015/backup'
Preparing archive operationsending incremental file list
/./
...
```

I do suspect that the part between:
`Creating disk layout`
and 
`Saving /root/rear/var/log/rear/rear-d2.log as rear-d2.log to usb location`
should not occur for `mkbackup`.

Is my presumption correct or incorrect?

**Comment by ProBackup-nl** [comment]
There is another potential recover issue

`rear recover` returns:

```
...
Running workflow recover...
Using backup archive '/tmp/rear.xyz/outputfs/rear/host/20170320.2106/backup'
ERROR: No 'backup' detected in '/tmp/rear.xyz/outputfs/rear/localhost/*'
Aborting due to an error, ...
```

**Comment by ProBackup-nl** [comment]
@jsmeix One unintended debug leftover is removed. The commenting of the debug section has now been uncommented.

This code not only introduces systemd-boot boot support. I needed to catch some situation to prevent execution from breaking, f.e. because of not existing commands, folders, etcetera.

Which code raises questions? I will then add some more comments to try to explain what and why.

**Comment by ProBackup-nl** [comment]
@gdha I did try to exclude usr/share/rear/skel/default/etc/scripts/system-setup from the git commit, though that failed due to my inexperience with `git`.

**Comment by gdha** [comment]
@ProBackup-nl any chance to rework the pull request?

**Comment by ProBackup-nl** [comment]
@gdha Am I correctly understand that:

> I think @schlomo is right that we first should detect where the ESP directory is located and use that in a variable, e.g. ESP_DIR

is referring to:
https://github.com/rear/rear/pull/1246#pullrequestreview-27076231
?

**Comment by ProBackup-nl** [comment]
@gdha I am stuck in pushing updates to this pull request:
```
# git push origin rear/rear#1214
To ssh://github.com/ProBackup-nl/rear.git
 ! [rejected]          rear/rear#1214 -> rear/rear#1214 (fetch first)
error: failed to push some refs to 'ssh://git@github.com/ProBackup-nl/rear.git'
```

Any changes that are not strictly related to systemd-boot support are now moved to separate pull requests.

**Comment by gdha** [comment]
@ProBackup-nl do a `git pull` first to fix the upstream modified files first. If that does not work I would discard this pull request and create a new one with an updated branch

**Comment by ProBackup-nl** [comment]
Status update: Let me figure out how to merge the conflicts
```
# git pull upstream master
From github.com:rear/rear
 * branch              master     -> FETCH_HEAD
   4fb1f98a..363eba71  master     -> upstream/master
Auto-merging usr/share/rear/rescue/default/100_hostname.sh
CONFLICT (content): Merge conflict in usr/share/rear/rescue/default/100_hostname.sh
CONFLICT (modify/delete): usr/share/rear/prep/default/500_guess_bootloader.sh deleted in 363eba7108d183432c32a7277f19b1a1c4b9067f and modified in HEAD. Version HEAD of usr/share/rear/prep/default/500_guess_bootloader.sh left in tree.
Auto-merging usr/share/rear/prep/default/320_include_uefi_env.sh
CONFLICT (content): Merge conflict in usr/share/rear/prep/default/320_include_uefi_env.sh
Auto-merging usr/share/rear/prep/default/310_include_uefi_tools.sh
CONFLICT (content): Merge conflict in usr/share/rear/prep/default/310_include_uefi_tools.sh
Auto-merging usr/share/rear/layout/save/default/450_check_bootloader_files.sh
CONFLICT (content): Merge conflict in usr/share/rear/layout/save/default/450_check_bootloader_files.sh
Auto-merging usr/share/rear/format/USB/default/300_format_usb_disk.sh
CONFLICT (content): Merge conflict in usr/share/rear/format/USB/default/300_format_usb_disk.sh
Removing usr/share/rear/backup/NETFS/GNU/Linux/30_stop_selinux.onhold
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by ProBackup-nl** [comment]
@gdha It seems I fixed the upstream modified files. I was even able to revert 0fd2f3b1 and 7917a0b. Now my limited knowledge makes me think that it is best to bring the rear/rear#1214 branch up to date with rear:master (instead of 87 commits behind rear:master) (How?). Then re-apply my changes, `commit` and `push`. Or do you have better suggestions?

**Comment by gdha** [comment]
@ProBackup-nl based on feedback I saw I think we better drop this pull request and start from scratch with first finding the ESP partition

**Comment by gdha** [comment]
As issue #1214 has been closed - we better close this PR request as well - until further notice.

**Pull request closed without merging**
