### PR TITLE
Borg as back end, now accepts options for repository encryption.

### PR DESCRIPTION
**Pull request by gozora**
- borg as back end, now accepts options for repository encryption.
- prune now only affects archives with BORGBACKUP_ARCHIVE_PREFIX

### CODE REVIEW

**Comment by gozora** [comment]
Hello all,
This patch adds possibility for remote Borg repository encryption.
I have however some mixed feelings about it. 
The thing on my mind is that we agreed in #1037 that we will mirror Borg defaults. (e.g. "none" compression will be used by default). Borg however uses encrypted repositories by default, which adds some additional complexity (manual repository initialization and entering pass-phrase for every repository operation like purging, listing, backing up). I've found couple of ways how to avoid all this (they are described [here](https://github.com/gozora/rear/blob/securing_borg/doc/user-guide/04-scenarios.adoc#bootable-iso-with-borg)), but like I said, mixed feelings...

In my opinion bare metal restore is quite complex task, where lot of things can go wrong,  and I really don't like adding more burden to quite stressed admin as they already have on their shoulders when dealing with restores (maybe because I'm one of them ;-) ). One such things could possibly be encrypted backups.

For this reason I'd like to ask for you opinion, if we could set **none** encryption as a default for ReaR and let users to enable encryption only if they really need to and possibly know what they are doing.
.
Thanks!

V.

**Comment by jsmeix** [comment]
I think we can set none encryption as a default for ReaR
because also for 'tar' there is no encryption and I assume
also for most other backup methods there is no encryption
so that I assume ReaR users would expect no encryption
by default.

Furthermore I think a basic idea behind ReaR is that the
actual recovery is as simple as possible, cf.
"A note on the meaning of 'Relax' in 'Relax-and-Recover'" in
https://en.opensuse.org/SDB:Disaster_Recovery
(excerpts):
<pre>
... after an experienced admin had set it up ...
...
When now a real disaster happens, even a
relatively unexperienced person can do the
recovery on the replacement hardware
(boot the rear recovery system, log in  as root,
 run "rear recover", and finally reboot). 
</pre>

@gozora 
currently this branch has conflicts that must be resolved:
Conflicting files: usr/share/rear/conf/default.conf

If you resolve the conflict, I would "just merge" it.

**Comment by gozora** [comment]
Jey, my first conflict, let me see :-)

**Comment by gozora** [comment]
Ok, looks like I've payed attention during my Git classes :-), conflict resolved.
I'll update defaults for encryption later today.

Thanks for now!

**Comment by jsmeix** [comment]
@gozora 
strange, when I click in this issue in the GitHub
web-fontend on "Files changed" I still see in
usr/share/rear/backup/BORG/default/50_make_backup.sh
and in
usr/share/rear/conf/default.conf 
your changes from https://github.com/rear/rear/pull/1044
that are already merged into rear master
so that I wonder if it has now really no conflicts?

**Comment by gozora** [comment]
Well, this conflict was rather strange. The conflict looked something like this:

```
<<<<<<< HEAD
=======
+BORGBACKUP_COMPRESSION=""
 +# Borg encryption type
 +# Types: none, keyfile, repokey
 +# none: encryption is disabled (least trouble with setup, least security)
 +# keyfile: passphrase and having-the-key (stored on client in /$HOME/.config/borg/keys/)
 +# repokey: passphrase-only (stored on server BORGBACKUP_REPO/config)
 +# Default: repokey
 +BORGBACKUP_ENC_TYPE=""
>>>>>>> <hash>
```

So to my understanding no conflict at all. I just removed `<<<<<<< HEAD`, `=======` and `>>>>>>> <hash>` 
`git add .`
`git commit`

and that is it ...

Maybe you've saw behavior like this already?

**Comment by gozora** [comment]
@jsmeix let's try to close this pull request and open new one,
What do you say?

**Comment by gozora** [comment]
@jsmeix FYI, by just clicking "new pull request", _usr/share/rear/backup/BORG/default/50_make_backup.sh_ is not between changed files any more.
So new, pull request might solve this ...

**Comment by jsmeix** [comment]
@gozora 
feel free to do it as it is best for you.
I think you can close this request yourself if you like
(I assume the one who creates it can also close it
but I cannot know how GitHub behaves for you).

**Comment by gozora** [comment]
#1046 was was opened instead.

**Pull request closed without merging**
