### PR TITLE
Fixes #781 Fix for removing directory in case that they are not empty

### LINKED ISSUE #781: Problem with making backup on S390X architecture
I have run the backup like obvious `rear -v mkbackup` but it doesn 't create a ISO image at all.
rear version:
`rear-1.17.2-4.el6.s390x`

~~~
# uname -a
Linux ibm-z10-52.rhts.eng.bos.redhat.com 2.6.32-573.el6.s390x #1 SMP Wed Jul 1 18:26:59 EDT 2015 s390x s390x s390x GNU/Linux
#
~~~
As you can see genisoimage binary is available on my S390X system:
~~~
# ls -la /usr/bin/mkisofs
lrwxrwxrwx. 1 root root 25 Feb 16 03:28 /usr/bin/mkisofs -> /etc/alternatives/mkisofs
# ls -la /etc/alternatives/mkisofs
lrwxrwxrwx. 1 root root 20 Feb 16 03:28 /etc/alternatives/mkisofs -> /usr/bin/genisoimage
# 
~~~

I have found that the last messages from log are from ./lib/framwork-functions.sh
Logs from backup.
~~~
# rear -v mkbackup
Relax-and-Recover 1.17.2 / Git
Using log file: /var/log/rear/rear-ibm-z10-52.log
Creating disk layout
Creating root filesystem layout
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Creating initramfs
# 
~~~

The problematic parts which I have found from log file are:
~~~
2016-02-17 03:40:25 Including layout/save/default/45_check_bootloader_files.sh
cat: /var/lib/rear/recovery/bootloader: No such file or directory
2016-02-17 03:40:25 Including layout/save/default/45_check_network_files.sh
~~~

~~~
2016-02-17 03:40:26 Including rescue/GNU/Linux/50_clone_keyboard_mappings.sh
Couldn't get a file descriptor referring to the console
2016-02-17 03:40:26 Including rescue/default/50_ssh.sh
~~~

~~~
2016-02-17 03:18:50 Including backup/default/00_valid_backup_methods.sh
2016-02-17 03:18:50 Finished running 'backup' stage in 0 seconds
2016-02-17 03:18:50 Finished running mkbackup workflow
2016-02-17 03:18:50 Running exit tasks.
rmdir: removing directory, `/tmp/rear.cjkmgymviIqDVNL/outputfs'
rmdir: failed to remove `/tmp/rear.cjkmgymviIqDVNL/outputfs': Directory not empty
2016-02-17 03:18:50 Finished in 15 seconds
2016-02-17 03:18:50 Removing build area /tmp/rear.cjkmgymviIqDVNL
rmdir: removing directory, `/tmp/rear.cjkmgymviIqDVNL'
2016-02-17 03:18:50 End of program reached

~~~

Do you know what's going on?

It seems that it is relevant only for S390X architecture.

I will send you a PR soon.
But ISO image is not generated at all.

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by pcahyna** [comment]
Hello, @phracek @gdha , why this change? It reverts the change in 8a545d608b7c4baf408ca1033458cd8a0ace5fdd and risks reintroducing bug #465. The point is, when the directory is not empty, you should not remove it, because it can contain valuable data, like previous backups or backups from other machines.
I also don't see how it fixes #781 (support for S/390), since I suspect the nonempty directory is a consequence of not having support for S/390, not the cause.

**Comment by pcahyna** [comment]
More general question, the function `cleanup_build_area_and_end_program` and the `AddExitTask` in 100_mount_output_path.sh seem to have the same purpose. Why do we have both?

Similar question applies to 
```bash
[[ -d $BUILD_DIR/outputfs/$NETFS_PREFIX ]] && rm -rf $v $BUILD_DIR/outputfs/$NETFS_PREFIX
[[ -d $BUILD_DIR/outputfs/$RSYNC_PREFIX ]] && rm -rf $v $BUILD_DIR/outputfs/$RSYNC_PREFIX
```
in usr/share/rear/output/default/980_umount_output_dir.sh although this part has not been touched by this change nor by 8a545d6. (I am asking because there seem to be way too many places where we rm -rf potentially valuable data.)

**Comment by pcahyna** [comment]
I also found that `rm` has a useful `--one-file-system` option. As ReaR does not support RHEL 5 anymore, we could start using it, unless there are some supported SLES versions that lack it (Debian 8 and Ubuntu 16.04 and RHEL 6 have it: http://manpages.ubuntu.com/manpages/xenial/man1/rm.1.html).

**Comment by jsmeix** [comment]
@pcahyna 
in general ReaR has grown according to what was needed in practice
by various different contributors over the time.
So we do have lots of duplicated convoluted, obfuscated, outdated,
quick-and-dirty, and whatever else kind of "bad code" places.
I tried to clean up several of them (those places where I was mostly hit)
as good as I could (with my limited overall knowledge of the whole picture).
So when you are hit by whatever kind of "bad code" place
feel free and be brave and merciless and try to clean up the mess.
Usually things won't get worse when you do it with some reasonable care.
Miracles are not expected (i.e. you may make mistakes - that's normal).
But please add meaningful and explanatory comments to your cleaned up code
to enable others to fix and enhance your code properly if needed later, cf.
https://github.com/rear/rear/wiki/Coding-Style

**Comment by pcahyna** [comment]
@jsmeix thanks for your encouragement, but I first wanted to learn the intent of the current code (in this case, duplication of output directory removal) before attemtoting any cleanup :-)

**Pull request merged**
