### PR TITLE
Remove dev null redirection where possible issue1395

### PR DESCRIPTION
**Pull request by jsmeix**
* Type: **Cleanup**

* Impact: **Low**

* Reference to related issue (URL):
https://github.com/rear/rear/issues/1395

* How was this pull request tested?
Not yet tested by me in any way and
I cannot test all those affected code parts,
in particulart not the changes for TSM and NBU.

* Brief description of the changes in this pull request:
Some general cleanup for ReaR 2.6. in all scripts
by removing '2>/dev/null' where it makes sense
and replacing '&>/dev/null' by '1>/dev/null' where it makes sense
or also removing '&>/dev/null' where that seems to be better, see
https://github.com/rear/rear/issues/1395#issuecomment-541083321

### CODE REVIEW

**Comment by jsmeix** [comment]
@schabrolles 
could you please - if time permits - have a look at my changes in
usr/share/rear/verify/TSM/default/390_request_point_in_time_restore_parameters.sh
and ideally verify that TSM still works for you with my changes?

@cge77
could you please have a look at my changes in
usr/share/rear/verify/NBU/default/390_request_point_in_time_restore_parameters.sh
and ideally verify that NBM NetBackup still works for you with my changes?

**Comment by cge77** [comment]
Hi jsmeix.

Where is your "usr/share/rear/verify/NBU/default/390_request_point_in_time_restore_parameters.sh"? I do not know how I can see it.


Regards.

**Comment by jsmeix** [comment]
@cge77 
the new version of
usr/share/rear/verify/NBU/default/390_request_point_in_time_restore_parameters.sh
from this pull request is here:

https://raw.githubusercontent.com/rear/rear/bd51a4c001dfa1b9934c1e15c3716056fdf8d6cc/usr/share/rear/verify/NBU/default/390_request_point_in_time_restore_parameters.sh

**Comment by jsmeix** [comment]
@cge77 @rear/contributors 
see also https://github.com/rear/rear/issues/2253

**Comment by jsmeix** [comment]
I "just merged" it so that things can be tested right now
as long as ReaR 2.6 is still under development.
Please report if there are regressions so that I can fix them.

**Comment by cge77** [comment]
Hi jsmeix.

I checked the script https://raw.githubusercontent.com/rear/rear/bd51a4c001dfa1b9934c1e15c3716056fdf8d6cc/usr/share/rear/verify/NBU/default/390_request_point_in_time_restore_parameters.sh but it is very different to my script. Sorry, but I cannot help much in this topic...


Best regards.

**Pull request merged**
