### PR TITLE
change debhelpers compat level to 10

### PR DESCRIPTION
**Pull request by DEvil0000**
due to warning about deprecation at least on ubuntu 22.04
```
dh_*: warning: Compatibility levels before 10 are deprecated (level 9 in use)
```
this should be changed

### CODE REVIEW

**Comment by jsmeix** [comment]
I know nothing at all about Debian/Ubuntu packaging
so I cannot review it - in particular I know nothing
whether or not that change could cause regressions
when building it on older Debian/Ubuntu versions.

@DEvil0000 
do you perhaps know if increasing that vaule could cause
regressions when building it on older Debian/Ubuntu versions?

The last increase (from 5 to 9) happened
on Jun 27, 2017 by @schlomo via
https://github.com/rear/rear/commit/56959b54fcf3ec02113fbf1f4281867270cf1170
so perhaps @schlomo might know if increasing that vaule
could cause regressions when building it on older
Debian/Ubuntu versions?

**Comment by jsmeix** [comment]
@gdha 
I noticed that also you did something in the past
for debian/Ubunto packaging, so perhaps you might know
if increasing the vaule in packaging/debian/compat
could cause regressions when building it on older
Debian/Ubuntu versions?

**Comment by DEvil0000** [comment]
I kinda know debian packaging but don't know the details of debhelpers. If there is a deprecation warning or such it is normally a good idea to follow the suggestion.

**Comment by jsmeix** [comment]
I think I will "just merge" it today afternoon.
If something breaks with package building under Debian/Ubuntu
we can fix it as needed (e.g. revert this change as a band aid).

**Comment by jsmeix** [comment]
@DEvil0000 
thank you for your continuous improvements of ReaR!

**Pull request merged**
