### PR TITLE
Avoid recreation of non-existing btrfs subvolumes (fix #1496)

### LINKED ISSUE #1496: Error during layout recreation with btrfs and docker
#### Basis

* rear version (/usr/sbin/rear -V): Relax-and-Recover 2.2 / Git
* OS version (cat /etc/rear/os.conf or lsb_release -a): Ubuntu 16.04.3 LTS
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): see below

#### Problem

Using `rear mkrescue` on a system with **docker** running on a **btrfs** file system makes a subsequent `rear recover` stop with the following error messages:
```
Mounting filesystem /
[  169.768852] BTRFS error (device sda2): '@/var/lib/docker/btrfs' is not a valid subvolume
An error occurred during layout recreation.
```
#### Workaround

Use `systemctl stop docker.service` before running `rear mkrescue`.

#### Probable root cause

Docker somehow manages to put a seemingly impossible entry in the kernel's notion of mounted file systems (`proc/self/mounts`):
```
# mount | grep docker
/dev/sda2 on /var/lib/docker/btrfs type btrfs (rw,noatime,nodiratime,ssd,space_cache,subvolid=257,subvol=/@/var/lib/docker/btrfs)
```

The option `subvol=/@/var/lib/docker/btrfs` breaks it. Btrfs subvolumes can be mounted by `subvolid=` or subvolume path (`subvol=`). In this example, `subvolid` 257 is the root subvolume and there is no such subvolume with a path of `@/var/lib/docker/btrfs` or `/@/var/lib/docker/btrfs`. Trying to mount such a beast manually fails:
```
# mount -t btrfs -o rw,noatime,nodiratime,ssd,space_cache,subvolid=257,subvol=/@/var/lib/docker/btrfs /dev/sda2 M
BTRFS error (device sda2): '/@/var/lib/docker/btrfs' is not a valid subvolume
# mount -t btrfs -o rw,noatime,nodiratime,ssd,space_cache,subvolid=257,subvol=@/var/lib/docker/btrfs /dev/sda2 M
BTRFS error (device sda2): '@/var/lib/docker/btrfs' is not a valid subvolume
```

This is the current list of relevant btrfs subvolumes (excluding volume snapshots named `.@*`):
```
# btrfs subvolume list -a / | grep -v '<FS_TREE>/.@'
ID 257 gen 105922 top level 5 path <FS_TREE>/@
ID 258 gen 105922 top level 5 path <FS_TREE>/@home
ID 5125 gen 27216 top level 257 path @/var/lib/docker/btrfs/subvolumes/8bfcbb9c775e910d504ac7d0f091e9668d700fffcc4c10e71118330ddad47b80
ID 5126 gen 27217 top level 257 path @/var/lib/docker/btrfs/subvolumes/4209efbc4922061100d9922741e2b5135d396a1586d1111f72d1beb9ea1cc513
ID 5127 gen 27218 top level 257 path @/var/lib/docker/btrfs/subvolumes/e44faf88d5e4a25366e7e0eb2882f40b1c0d2b5fef1142f06b0dad3cd4e1ee4f
ID 5128 gen 27219 top level 257 path @/var/lib/docker/btrfs/subvolumes/268b6c560568411d38215d3d87c08ddc0fb373bb02b4d1a114c589c790a69101
ID 5129 gen 28716 top level 257 path @/var/lib/docker/btrfs/subvolumes/4c48e4299061b98be208013f5be89f05107f075fea4c4e659f117fa55225971b
ID 5134 gen 80934 top level 257 path @/var/lib/docker/btrfs/subvolumes/e18c9690831dd193f37d5dadf0e0ff0f9cac75e6bba09e5b471b7a16538e639b
ID 5137 gen 80934 top level 257 path @/var/lib/docker/btrfs/subvolumes/813f7476ee473d6a1e64b4e08877b0fd76ce0e6a472dfea8ca4f44711e545946
ID 5149 gen 80934 top level 257 path @/var/lib/docker/btrfs/subvolumes/1f45e82870cc392d533d0976f2e1a732b8fab8b85f322ae77533c8cfd676dbff
ID 5311 gen 80934 top level 257 path @/var/lib/docker/btrfs/subvolumes/86c787fc596f7f11931fdc6403ad713014d36b958464012d73b8940460cd2664-init
ID 5312 gen 80934 top level 257 path @/var/lib/docker/btrfs/subvolumes/86c787fc596f7f11931fdc6403ad713014d36b958464012d73b8940460cd2664
```

#### What to do

I have no idea why the docker folks did this, but since this stuff is out in the wild, I'd like to convince ReaR to just ignore anything that looks like a docker-generated subvolume (snapshot or not). AFAIK, these btrfs docker-trees cannot be safely restored anyway in a consistent fashion.

I've tried to use `EXCLUDE_RECREATE=("${EXCLUDE_RECREATE[@]}" "fs:@/var/lib/docker/btrfs")` but apparently this doesn't match. Is there any overview documentation on how the exclusion mechanism actually works. Any hints where I should look?

### PR DESCRIPTION
**Pull request by OliverO2**
This PR makes sure that a btrfs subvolume actually exists before trying to recreate it.

See #1496.

### CODE REVIEW

**Comment by jsmeix** [comment]
@OliverO2 
from plain looking at the code everything looks perfect!

I only wonder about the reason behind
why you added a new lib/btrfs-functions.sh script
and did not add your btrfs_subvolume_exists function
to the existing lib/filesystems-functions.sh script?

**Comment by OliverO2** [comment]
@jsmeix 

Yes, I had considered `filesystems-functions.sh` but somehow decided against it. I agree that the content of `btrfs-functions.sh` could just go there. Would be simpler and more logical.

**Comment by jsmeix** [comment]
If there are no objections I will merge it soon...

**Comment by OliverO2** [comment]
@jsmeix 
While we're dealing with btrfs code, would you mind stripping the `#btrfssnapshotsubvol` comments from `disklayout.conf`?

Over here, disklayout.conf contains 268 lines, 213 of them (86%) are `#btrfssnapshotsubvol` comments. That makes it difficult to review and edit the file, especially if done via a console with limited screen real estate.

What about just putting just a comment about the number of snapshot volumes encountered in disklayout.conf and put the snapshot paths in the log file only?

**Comment by jsmeix** [comment]
@OliverO2 
for SUSE I have the btrfs snapshot subvolumes intentionally
listed in disklayout.conf but disabled from recreation.
At SUSE we can boot from a btrfs snapshot subvolume
when it was made by the SUSE tool 'snapper' - i.e. each
snapper btrfs snapshot subvolume could be used as
the subvolume that gets mounted at the '/' mountpoint.
Therefore I would like to have them listed in disklayout.conf.

In your case according to your valuable explanation in
https://github.com/rear/rear/issues/1496#issuecomment-329824117
"We snapshot each volume every 5 minutes"
you get tons of btrfs snapshot subvolumes which fill up
the disklayout.conf file with mostly useless information.

I suggest to provide another config variable so that the
user can specify if he wants to have btrfs snapshot subvolumes
listed in disklayout.conf
or
your existing support for EXCLUDE_RECREATE for btrfs
could be somehow enhanced to be also used to get btrfs
snapshot subvolumes completely ignored
e.g. via something like
<pre>
EXCLUDE_RECREATE=( "${EXCLUDE_RECREATE[@]}" "btrfssnapshotsubvol:all" )
</pre>
where a special qualifier like 'all' could mean that all btrfs
snapshot subvolumes get completely ignored
or
whatever else you like.

I only like that by default btrfs snapshot subvolumes
are still listed (but disabled) in disklayout.conf.

**Comment by jsmeix** [comment]
I have tested that a ReaR recovery still works
with the SUSE SLES12-SP2 default btrfs structure.

**Pull request merged**
