### PR TITLE
Generate AUTHORS file

### PR DESCRIPTION
**Pull request by jsmeix**
Generated AUTHORS file according to
https://github.com/rear/rear/issues/1427#issuecomment-317380362

I don't see a reason to omit contributions with less than
about 15 lines of code according to
https://www.gnu.org/prep/maintain/html_node/Legally-Significant.html#Legally-Significant
because I assume that contributions with less than
about 15 lines of code are not legally significant
applies perhaps only fot U.S. laws but for other countries
any contributed line of code could be legally significant
so that I like to be on the safe side and list all contributors.
It costs nothing to list them all in a generated AUTHORS file
compared to carefully exclude some of them.

### CODE REVIEW

**Comment by gozora** [comment]
@schlomo addresses have been exposed already :-) so not much we can do about it now ...

@jsmeix 
I've run your script as follows, just to sum up lines of individual contributor(s) and compare them to [contributors page](https://github.com/gozora/rear/graphs/contributors).
```
./jsmeix.sh | grep gratien | awk '{ sum += $1} END {print sum}'
```
For @gdha I've got 16 307 lines, comparing to Githubs 21 945 lines.

I basically don't care about this, but it might become confusing to have two quite different numbers for one metric ...

V.

**Comment by schlomo** [comment]
@gozora I don't want my old emails, partially also from companies I don't longer work at, to be exposed and made visible in this fashion. In the git history it is obvious to the reader when this email was current. In such a summary file it is not.

What about people who changed their name or email? We'll list them multiple times even though this is the same person. Pulling this info from GitHub would actually normalize it as GitHub tracks (I hope at least) the person and not the name or email.

The more I think about it the more I don't feel well about putting the list of names and emails like this without the context (on the time line).

**Comment by gozora** [comment]
@schlomo I guess you've just misunderstood my https://github.com/rear/rear/pull/1428#issuecomment-317462874 ...
All I was referring to what that once you put something publicly on the Internet it is exposed. So once this PR was created, these data are out and we don't need to ask anybody if he allows us to publish his/her mail address or not ;-).

I know that there are people out there who really care about all the things you've mentioned, and I fully understand that!

V.

**Comment by schlomo** [comment]
@gozora time does play a role. If we delete this PR quickly then not all search engines will have picked it up. And all search engines drop pages that disappear so that those emails would not be so prominently in the search index.

A static AUTHORS file with all the emails carries much more weight with the search engines. And it looks like "official" data.

**Comment by gozora** [comment]
@schlomo  I think that 5 hours is long enough to have this PR already indexed, apart from that you'd need to remove branch of @jsmeix as well.
But if you think that this is really bad thing, you should close/remove it ...

V.

**Comment by jsmeix** [comment]
I close this one because it is superseded by
https://github.com/rear/rear/pull/1429

@gozora 
regarding the different numbers in your
https://github.com/rear/rear/pull/1428#issuecomment-317462874
I think my numbers are lower because I omitted
certain things like whitespace changes as I described in
https://github.com/rear/rear/issues/1427#issuecomment-317380362
but there could be also a bug somewhere in my script.
I am a mathematician - I cannot count ;-)

**Comment by jsmeix** [comment]
For the fun of scariness:
I guess search engines already dig through source code archives
(from plain tar archives up to git checkouts and things like that)
to harvest personal data like names with e-mail addresses.

**Pull request closed without merging**
