### PR TITLE
500_make_backup.sh: fix exit code logic

### PR DESCRIPTION
**Pull request by casantos**
* Type: **Bug Fix**

* Impact: **Normal**

* Reference to related issue (URL): https://github.com/rear/rear/pull/2466#issuecomment-669168386

* How was this pull request tested?

Ran a backup ensuring that there is not enough space in the destination to write backup.tar.gz.

* Brief description of the changes in this pull request:

Commit 2674807 removed the BACKUP_PROG_CRYPT_OPTIONS="cat" which breaks
the exit code logic because pipes_rc and backup_prog_shortnames does no
longer match.

Ensure that the number of elements in both variables are alwas the same.

Signed-off-by: Carlos Santos <casantos@redhat.com>

### CODE REVIEW

**Comment by jsmeix** [comment]
What I like more with your implementation here
compared to my https://github.com/rear/rear/pull/2472
is that this one here avoids the useless use of cat as dummy.

Now I am wondering if we could also get rid of the useless use of `dd`
in the other default case when the backup should not be split
with reasonable effort.

On the other hand
https://github.com/rear/rear/issues/2265
means a complete cleanup of both 500_make_backup.sh
and 400_restore_backup.sh needs to be done at some time anyway.
 
I wonder if that overall cleanup should be done now or if it is better for now
to not change too much now at once in an hurry and only fix things as they
have been known to work which I did in https://github.com/rear/rear/pull/2472

**Comment by casantos** [comment]
> What I like more with your implementation here
> compared to my #2472
> is that this one here avoids the useless use of cat as dummy.
> 
> Now I am wondering if we could also get rid of the useless use of `dd`
> in the other default case when the backup should not be split
> with reasonable effort.
> 
> On the other hand
> #2265
> means a complete cleanup of both 500_make_backup.sh
> and 400_restore_backup.sh needs to be done at some time anyway.
> 
> I wonder if that overall cleanup should be done now or if it is better for now
> to not change too much now at once in an hurry and only fix things as they
> have been known to work which I tried via #2472

I'm not against a deep overhauling but I'd prefer to do it in baby steps.

**Comment by jsmeix** [comment]
@rear/contributors 
I would like to merge it tomorrow morning provided there are no objections.

**Comment by jsmeix** [comment]
@casantos 
thank you for the fix!

**Pull request merged**
