### PR TITLE
issue: #3018: fix sesam default exlude pathes

### PR DESCRIPTION
**Pull request by abbbi**
fix for issue #3018

### CODE REVIEW

**Review by jsmeix — APPROVED** [review]

**Comment by jsmeix** [comment]
@rear/contributors 
could you review this pull request (if time permits)?

**Comment by jsmeix** [comment]
Those 'Code scanning / Shellcheck (reported by Codacy)'
are from Codacy, cf.
https://github.com/rear/rear/commit/3cb64f1262eac953b78eec515b1ca561aa1c5b6b

See also
https://github.com/rear/rear/pull/2991#issuecomment-1573522079
and the subsequent comments, in particular see
https://github.com/rear/rear/pull/2991#issuecomment-1573690998
```
... it seems that Codacy simply calls plain 'shellcheck' ...
```
and
https://github.com/rear/rear/pull/2991#issuecomment-1573799743

**Comment by jsmeix** [comment]
@rear/contributors 
I would like to merge it today afternoon
unless objections appear.

FYI regarding ShellCheck:
Our own "Differential ShellCheck" (which is deliberately set up
exactly as currently needed in ReaR) does not report issues.

**Comment by schlomo** [comment]
Yes, please merge. Can we disable those extra shellcheck errors from Codacy?

**Pull request merged**
