### PR TITLE
Allow backup to be stored in ISO for ppc64/ppc64le

### PR DESCRIPTION
**Pull request by schabrolles**
As said in [#697(comment)](https://github.com/rear/rear/issues/697#issuecomment-307706989), syslinux package (which provide `isolinux`) is only available for x86 arch.

I proposed to adapt x86 scripts for POWER (ppc64/ppc64le)

1) usr/share/rear/output/ISO/Linux-ppc64le/800_create_isofs.sh
removing creation of iso (will be done by new script 820_create_image_iso.sh)

2) usr/share/rear/output/ISO/Linux-ppc64le/810_prepare_multiple_iso.sh
(New script) create multiple iso when needed. it can be linked to `Linux-i386/810_prepare_multiple_iso.sh` (no ppc64 specific)

3) usr/share/rear/output/ISO/Linux-ppc64le/820_prepare_multiple_iso.sh
(New script) create iso file. need to use a "specific" ppc64le script as there is no `isolinux`on ppc64le

Note: ppc64 scripts are the same as ppc64le (can be linked)

This pull request help to answer to #697 #1375

### CODE REVIEW

**Comment by jsmeix** [comment]
@schabrolles 
currently the automated Travis test fails with
<pre>
./usr/share/rear/output/ISO/Linux-ppc64/800_create_isofs.sh: No such file or directory
</pre>
I think this is because a symlink does not use a relative path.

I think it is the symlink
<pre>
usr/share/rear/output/ISO/Linux-ppc64/800_create_isofs.sh
</pre>
that seems to point to
<pre>
usr/share/rear/output/ISO/Linux-ppc64le/800_create_isofs.sh
</pre>
but I think it should actually point to
<pre>
../Linux-ppc64le/800_create_isofs.sh
</pre>

**Comment by jsmeix** [comment]
@schabrolles 
when you are working on that scripts
could you also replace all
<pre>
>&8
</pre>
with
<pre>
>&2
</pre>
cf. https://github.com/rear/rear/pull/874#issuecomment-227135652
and https://github.com/rear/rear/pull/1365
plus https://github.com/rear/rear/pull/1359#discussion_r116239195
and the new "What to do with stdout and stderr" in
https://github.com/rear/rear/wiki/Coding-Style

**Comment by jsmeix** [comment]
@schabrolles 
please tell when we can merge it.
Currently there is no 810_prepare_multiple_iso.sh
but I think - at least for now - only documentation
about the limitations is sufficient, cf.
https://github.com/rear/rear/issues/697#issuecomment-309406317

**Comment by jsmeix** [comment]
Oops - I overlooked the
usr/share/rear/output/ISO/Linux-ppc64le/810_prepare_multiple_iso.sh
link that point to +../Linux-i386/810_prepare_multiple_iso.sh

@schabrolles 
does this mean even multiple ISOs work on POWER now?

**Comment by schabrolles** [comment]
@jsmeix 
Yes, it works with multiple ISO on POWER..... as x86 (tested with RHEL7)
and you are right, I used the x86 version of `810_prepare_multiple_iso.sh` as we don't need a ppc64/ppc64le specific script for that.

**Comment by jsmeix** [comment]
@schabrolles 
wow!

I will "just merge" it.

**Pull request merged**
