### PR TITLE
Replace possibly misleading "USB device" by generic "USB or disk device" wording

### PR DESCRIPTION
**Pull request by jsmeix**
* Type: **Minor Bug Fix** / **Enhancement**

* Impact: **Normal**

* Reference to related issue (URL):
https://github.com/rear/rear/issues/2588

* How was this pull request tested?
Not tested - basically only message text changes.

* Brief description of the changes in this pull request:
Replace possibly misleading "USB device" by generic "USB or disk device" wording

### CODE REVIEW

**Comment by jsmeix** [comment]
Instead of replacing "USB device" by pure "disk device"
I replaced "USB device" by "USB or disk device" to indicate with the word "USB"
that those messages belong to the `OUTPUT=USB` method
which is primarily meant to be used with "USB disk like thingies"
(i.e. removable disks that are usually attached via USB)
e.g. USB mass storage devices like USB sticks or USB disks.

**Comment by pcahyna** [comment]
What about saying "Block device" instead of "USB or disk device"?

**Comment by jsmeix** [comment]
@pcahyna 
I think "block device" is technically 100% right
but mostly meaningless for the user because
basically all devices in ReaR are block devices
so one could also say only "device" which is never wrong
but completely meaningless as a superflous word like "thingy".

The general problem with the `USB` stuff in ReaR is that it was added
to fulfill a specific requirement of a specific ReaR customer's use case
so that the `USB` stuff in ReaR behaves somewhat special and different
compared to other methods, i.e. `USB` is somewhat incompatible, cf.
https://github.com/rear/rear/issues/2588#issuecomment-805658626

**Comment by jsmeix** [comment]
If there are no objections that "USB or disk device" is wrong
i.e. if "USB or disk device" is "good enough" at least for now
I would like to merge it today afternoon.

**Pull request merged**
