### PR TITLE
Allowing multipath devices to be candidate disk during mapping.

### PR DESCRIPTION
**Pull request by schabrolles**
During migration, ReaR recovery propose candidate disk if they have the same (or bigger) size than the original.
The problem is that size of mulitpath device is currently not stored in layout file:

This patch propose :
 - To store multipath device size in `$LAYOUT_FILE`
 - Add line beginning by multipath to be part of the comparison process when searching for device with the same size or finding unmapped candidate.

### CODE REVIEW

**Comment by gdha** [comment]
@schabrolles Is this part 1 of a pull request? Or am I missing the point here?

**Comment by schabrolles** [comment]
@gdha You are right in a way.
This pull request treat what we have to modify to have a multipathed disk proposed as a replacement disk during migration.
- (before this one) You will need (#1309) to activate multipath if you migrate from non-multipathed to multipathed with `BOOT_OVER_SAN=y` 
- (after in the process) You will nedd (#1315) to properly map the old <=> new device with good multipath partition naming.

**Comment by jsmeix** [comment]
@schabrolles 
in layout/save/GNU/Linux/280_multipath_layout.sh
you inserted output of $dm_size in the 'multipath' lines
in $DISKLAYOUT_FILE via
<pre>
echo "multipath /dev/mapper/$dm_name $dm_size ${slaves%,}" >> $DISKLAYOUT_FILE
</pre>
but I miss adapted code where those 'multipath' lines are input
because now ${slaves%,} has become the third parameter
(before it was the second parameter).

As far as I see
layout/prepare/GNU/Linux/210_load_multipath.sh
does not need adaptions because it only
uses the first parameter /dev/mapper/$dm_name

As far as I see also
layout/save/default/335_remove_excluded_multipath_vgs.sh
does not need adaptions because it also only
uses the first parameter /dev/mapper/$dm_name

Now I wonder where ${slaves%,} is used at all?

If ${slaves%,} is nowhere used we should remove it.

**Comment by jsmeix** [comment]
I think I found where ${slaves%,} is used: In
layout/save/default/320_autoexclude.sh
(which is run after layout/save/GNU/Linux/280_multipath_layout.sh)
as
<pre>
while read multipath device slaves junk ; do
...
done < <(grep ^multipath $LAYOUT_FILE)
</pre>
where now "read multipath device slaves junk"
must become "read multipath device dm_size slaves junk"

Furthermore with positional parameters
one must ensure no positional parameter is empty
so that in layout/save/GNU/Linux/280_multipath_layout.sh
plain
<pre>
dm_size=$(cat /sys/block/$name/size)
</pre>
is not fail-safe and must be at least
<pre>
dm_size=$(cat /sys/block/$name/size)
test "$dm_size" || Error "Failed to get /sys/block/$name/size"
</pre>
so that it errors out early during "rear mkbackup/mkrescue"
instead of blindly proceed and let it fail arbitrarily later
because "read multipath device dm_size slaves junk"
reads wrong parameters when dm_size is empty.

**Comment by schabrolles** [comment]
@jsmeix, Yes I've also checked before inserting `$dm_size` at the second position (like disk).
Each time this line is "parsed" with read, `${slaves%,} ` are put in a variable named `junk` ... meaning useless :-) ...
But I would prefer to keep slaves in the LAYOUT file (always at the end of the line => to be "junked").
It will allow verification when reading LAYOUT files to understand why some disk are commented (sda, sdb ...) => because they are part of a multipath device.

**Comment by jsmeix** [comment]
Same in
layout/prepare/default/520_exclude_components.sh
<pre>
while read multipath device slaves junk ; do
...
done < <(grep ^multipath "$LAYOUT_FILE")
</pre>
must now be
<pre>
while read multipath device dm_size slaves junk ; do
</pre>

**Comment by jsmeix** [comment]
FYI:
See https://github.com/rear/rear/issues/718 regarding
DISKLAYOUT_FILE versus LAYOUT_FILE inconsistency.

**Comment by schabrolles** [comment]
@jsmeix Good catch... I will do this.

**Comment by schabrolles** [comment]
@jsmeix Do you want me to change LAYOUT_FILE to DISKLAYOUT_FILE in 
- layout/save/default/320_autoexclude.sh
- layout/prepare/default/520_exclude_components.sh

**Comment by schabrolles** [comment]
@jsmeix it seems that the latest changes in `layout/save/default/320_autoexclude.sh`
and `layout/prepare/default/520_exclude_components.sh` brake the recovery process when recover from (multipath) => (non-mulitpath). In the other way, it is working.
I need more time to understand what is happening here.

**Comment by schabrolles** [comment]
@jsmeix, I think I found it.

 `generate_layout_dependencies` needed to be updated for multipath after the addition of dm_size parameter at field 2. (cf commit dd65bd0). 
This change shifts the slave disk at field 3.

**Comment by jsmeix** [comment]
@schabrolles 
many thanks for your careful testing.
That positional parameters in LAYOUT_FILE / DISKLAYOUT_FILE
make things fragile and caused several weird looking issues
in the past where things fell apart at totally unexpected places :-(

**Comment by schabrolles** [comment]
@jsmeix if I understand well, we should use `$DISKLAYOUT_FILE` each time we want to use `/var/lib/rear/layout/disklayout.conf` ... So if you want, I can start to make the changes in the files used in this pull request. 

What do you think ?

**Comment by jsmeix** [comment]
@schabrolles 
I would very much appreciate it when one same name
is used for one same thing.

To fix the DISKLAYOUT_FILE versus LAYOUT_FILE
inconsistency please do it in a separated pull request
for https://github.com/rear/rear/issues/718
after the current pending pull requests were merged.

I fear there is perhaps some obscure reason why
different variable names are used?

I would prefer to keep separated issues separated (KSIS;-)
and not mix them up in one pull request (cf. RFC 1925 item 5).

**Comment by schabrolles** [comment]
@jsmeix I've finished my test and the migration works for all of the tests.

I only have one issue regarding xfs with rhel7 when moving from multipath to not multipath .... but it is not related to this pull request. I will investigate and open another pull request/issue if needed.

**Pull request merged**
