### PR TITLE
Fix btrfsmountedsubvol exclusion and dependency management

### PR DESCRIPTION
**Pull request by OliverO2**
This PR closes the existing gap between 'fs'-type file systems and mounted btrfs subvolumes (type 'btrfsmountedsubvol').

- It allows mounted btrfs subvolumes to be excluded like other components, for example:
```
EXCLUDE_RECREATE=( "${EXCLUDE_RECREATE[@]}" "btrfsmountedsubvol:/mnt/dir" )
```

- It enables dependency management for mounted btrfs subvolumes (making sure that file systems containing btrfs mount points are recreated as well).

Related: #1496

Tested on Ubuntu 16.04.3 LTS

### CODE REVIEW

**Comment by jsmeix** [comment]
@OliverO2 
as far as I see this is basically an additional enhancement
where no existing btrfs behaviour in ReaR could be changed.
From plain looking at the code the cleanup of the 'lvmdev' and
'swap' cases into the 'fs|btrfsmountedsubvol|swap|lvmdev' case
does not change any behaviour in ReaR.
If I am right, I would "just merge" it.

@OliverO2 
I also see and I do very much appreciate it
that you replace meaningless, misleading, and confusing
names like the dummy read variable 'done' (it hurts my eyes
when I see a variable named e.g. as a shell keyword ;-)
with a proper name. Many thanks for that!

**Comment by jsmeix** [comment]
Of there are no objections I will merge it soon...

**Comment by jsmeix** [comment]
I have tested that a ReaR recovery still works
with the SUSE SLES12-SP2 default btrfs structure.

**Comment by jsmeix** [comment]
This pull request introduced another regression via
https://github.com/rear/rear/commit/72810e9594d121ee12b5d8394c9fc9daa31ce749
in the generate_layout_dependencies() function
in usr/share/rear/lib/layout-functions.sh via this change (excerpt)
<pre>
-                done < <(grep "^fs" $LAYOUT_FILE)
+                done < <(awk '$1 ~ /^fs|btrfsmountedsubvol$/ { print; }' $LAYOUT_FILE)
</pre>

On SLES11 with btrfs and separated boot partition the
disklayout.conf file can contain a (correctly) commented entry like:
<pre>
#btrfsmountedsubvol /dev/sda3 / rw
<pre>
that matches the above new oversophisticated `awk`-ward code
so that during "rear recover" in the diskdeps.conf file
something like the following false dependency appears
<pre>
fs:/boot #btrfsmountedsubvol:/
</pre>
but because the correctly commented `#btrfsmountedsubvol` component
will never be created and because `fs:/boot` (i.e. the filesystem creation
of the 'boot' partition) now falsely depends on that `#btrfsmountedsubvol`
component the filesystem of the 'boot' partition gets also not created and
"rear recover" fails in layout/prepare/default/600_show_unprocessed.sh with
<pre>
No code has been generated to recreate fs:/boot (fs)
To recreate it manually add code to diskrestore.sh or abort.
</pre>

The right (and minimal - i.e. KISS) change should have been
<pre>
-                done < <(grep "^fs" $LAYOUT_FILE)
+                done < <(egrep '^fs |^btrfsmountedsubvol ' $LAYOUT_FILE)
</pre>
so that no such false `#btrfsmountedsubvol` dependency would be created
because commented entries in disklayout.conf would no longer match.

**Comment by jsmeix** [comment]
I fixed it via
https://github.com/rear/rear/commit/88f6d22a3b3812d1ca33cbf06000aafd352fabe1

**Comment by jsmeix** [comment]
@OliverO2 
could you verify if things still work for your particular use case with my
https://github.com/rear/rear/commit/88f6d22a3b3812d1ca33cbf06000aafd352fabe1

**Comment by jsmeix** [comment]
@OliverO2 
thank you for your prompt reply!

**Comment by OliverO2** [comment]
@jsmeix Always a pleasure. Thanks for your fix!

**Pull request merged**
