### PR TITLE
Make SLES12GA btrfs recovery work again (related to issue 1796)

### PR DESCRIPTION
**Pull request by jsmeix**
* Type: **Bug Fix**

* Impact: **High**

* Reference to related issue (URL):
https://github.com/rear/rear/issues/1796#issuecomment-388753131

* How was this pull request tested?
Both
recovery of SLES12-GA/SP0 with its default btrfs structure and
recovery of SLES12-SP3 with "LVM-based Proposal" (and the default btrfs structure)
work for me.

* Brief description of the changes in this pull request:

In usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
the code that ecludes/disables/comments btrfs subvolumes that belong to snapper
in disklayout.conf is now conditionally run only if there is
a SLES12-SP1 (and later) btrfs subvolumes setup
(i.e. when the default subvolume path contains `@/.snapshots/`),
cf. https://github.com/rear/rear/issues/1796#issuecomment-388763887

Additionally I simplified `SLES12SP1SP2_...` named variables to `SLES12SP1_...`
and changed texts like `SLES 12 SP1 and SP2` to `SLES 12 SP1 (or later)`
because the btrfs structure in SLES12 is the same since SP1 and later.

### CODE REVIEW

**Comment by jsmeix** [comment]
@schabrolles 
if you have time for it I would very much appreciate it if you could test it.

I need to merge it tomorrow to get that into the upcoming SLES15.

**Comment by schabrolles** [comment]
@jsmeix, Sorry, I'm a bit busy today
I'm gonna test the master branch against my SLES12 this weekend.
Do you know a way to simulate a SLES12SP0 from a SLES12SP2 without reinstalling from SP0 DVD?

**Comment by jsmeix** [comment]
@schabrolles 
no worries - I am also a bit too busy this days.

I cannot imagine how to simulate a SLES12SP0 installation from a SLES12SP2 DVD
because for a SLES12SP0 installation you need a SLES12SP0 installation system
with the SLES12SP0 installer (i.e. YaST of SLES12SP0) so that
you need a SLES12SP0 DVD with the SLES12SP0 YaST on it,
cf. my intentionally a bit overexact wording in
https://github.com/rear/rear/issues/1796#issuecomment-389775698
that I edited right now to make it even more unambiguous
<pre>
When I install a SLES12-GA/SP0 system
from an original SUSE SLES12-GA/SP0 installation medium
with its original SUSE SLES12-GA/SP0 installer
(i.e. the YaST installer on that SLES12-GA/SP0 installation medium)
on a virtual KVM/QEMU machine with a single 20GiB virtual harddisk
I get when I select the "LVM-based Proposal" in YaST
this result in the installed system
</pre>
versus
<pre>
When I install a SLES12-SP3 system
from an original SUSE SLES12-SP3 installation medium
with its original SUSE SLES12-SP3 installer
(i.e. the YaST installer on that SLES12-SP3 installation medium)
on a virtual KVM/QEMU machine with a single 20GiB virtual harddisk
I get when I select the "LVM-based Proposal" in YaST
this result in the installed system:
...
</pre>

For the fun of it you may even have a look at
https://en.opensuse.org/openSUSE:Bug_reporting_FAQ
that reads (excepts)
<pre>
People got mad at me because I entered "Install openSUSE x.y-Beta-z"
in Bugzilla's "how to reproduce" field. Why?
...
What we really need to know is what you did and how you did it - like
"boot from CD1, select "Installation", select language "Klingon", leave
the installation settings as they are, confirm installation, watch as
your hard disk goes up in flames."

And no, this really, really isn't nitpicking - we have so many installation
modes and so many installation paths that it takes ages to figure
all that out from the log files.
</pre>
;-)
Have a nice weekend!

**Comment by schabrolles** [comment]
@jsmeix,

I've just tested the master branch with #1813 merged against sles12sp2 only as I don't really have time to reinstall a SP0. I can just confirm that everything is still working well (no new side-effect)
- Backup / Restore on the same Guest: OK
- Migration (restore on a new system): OK

**Pull request merged**
