### PR TITLE
FDR application shared lib fix

### PR DESCRIPTION
**Pull request by mutable-dan**
support for vendor library built with rpaths, need rear to pass the ldd test by adding ld_library_path

### CODE REVIEW

**Comment by mutable-dan** [comment]
not sure why it's showing commits from pull 2142, were some commits already accepted upstream?  this pull request is a fork of my master.

**one change made to line 80 of 990_verify_rootfs**
```
if test "$BACKUP" = "FDRUPSTREAM" ; then
    # Use a FDRUPSTREAM-specific LD_LIBRARY_PATH to find FDR libraries
    # see https://github.com/rear/rear/issues/1533
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:opt/fdrupstream/bin
fi
```

**Comment by jsmeix** [comment]
@mutable-dan 
thank you for the LD_LIBRARY_PATH fix for BACKUP = FDRUPSTREAM!

I did the actually intended change in this pull request directly via
https://github.com/rear/rear/commit/cb698ffe3bd641ff7cdd67482e482f6fff4f6810

I cannot merge this pull request because it contains lots of changes
from the totally unrelated https://github.com/rear/rear/pull/2142

@mutable-dan 
to avoid that differnt issues get mixed up in pull requests
you may have a look at the "Contributing" section in
http://relax-and-recover.org/development/
how to keep separated things separated in git.
Therein follow in nparticular the `this article` link that points to
https://2buntu.com/articles/1459/keeping-your-forked-repo-synced-with-the-upstream-source/
which is in my opinion the best description how to work
with git and GitHub (at least thgis is how I finally managed
to work continuously and cleanly with git and GitHub).

**Comment by jsmeix** [comment]
A note FYI:

I think
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:opt/fdrupstream/bin
```
won't work because `opt/fdrupstream/bin` is a relative directory.
I think `/opt/fdrupstream/bin` is actually intended.
Because in default.conf there is
```
FDRUPSTREAM_INSTALL_PATH="/opt/fdrupstream"
```
I used in my
https://github.com/rear/rear/commit/cb698ffe3bd641ff7cdd67482e482f6fff4f6810
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$FDRUPSTREAM_INSTALL_PATH/bin
```

**Comment by mutable-dan** [comment]
i actually have a feature branch and was keeping our trunk in sync with your trunk.  i think i messed it up when i was playing with rebasing a while ago.   after the s390, we will fix our trunk

thx for handing the pull manually.  i will remove the this ork

**Pull request closed without merging**
