### PR TITLE
Adding support for FDRUPSTREAM

### PR DESCRIPTION
**Pull request by rowens275**
Initial support for FDR/Upstream restores to Intel-based Linux systems.

### CODE REVIEW

**Comment by gdha** [comment]
@rowens275 Could you also write a small section of documentation which we could add to http://relax-and-recover.org/documentation/usecases ? Thanks - all bits help ;-)

**Comment by rowens275** [comment]
Should I post the documentation here, or add it as a file in my pull request?

**Comment by gdha** [comment]
You may add it as a pull request with this issue if the documentation is part of rear product itself or as a pull request to the web-site https://github.com/rear/rear.github.com if you want to add or modify some web pages. Thanks!

**Comment by rowens275** [comment]
I will provide doc for the website and doc to be included in ReaR.  Should I be updating rear-release-notes.txt or do you guys do that?  Should I update rear-presentation.adoc to add to the list of Back-up backends?  Do you prefer the ReaR doc be in the same pull request, or should I upload a "doc" branch?

**Comment by schlomo** [comment]
For each GitHub Repo we need one pull request. One for rear itself (and the included documentation files) and another one for the rear.githhub.com website repo to update the stuff on the website. Feel free to add the info you seem appropriate with a link to your product.

**Comment by rowens275** [comment]
OK, the rear pull request should be ready.  I will work on the rear.github.com pull request now.

**Pull request merged**
