### PR TITLE
Update README.adoc and removal of .travis.yml

### PR DESCRIPTION
**Pull request by hpannenb**
Removed Travis CI status due to not working (any more).

##### Pull Request Details:

* Type: **Other**

* Impact: **Low**

* Reference to related issue (URL): #2757
 
* How was this pull request tested? Not required.

* Brief description of the changes in this pull request:
The current Travis CI integration is not working any more so its linked build status provides a misleading information and thus has been removed. The travis specific configuration file will also been removed with this PR.

### CODE REVIEW

**Comment by pcahyna** [comment]
Hi @antonvoznia, please have a look at the removed `.travis.yml`. I believe the same will be trivial to implement using Packit (as it builds RPMs, it already does the equivalent of `make install`, and `make validate` can be easily added to the `%check` section of the spec file).

**Review by jsmeix — APPROVED** [review]
I know nothing at all about Travis
but as the currently used does no longer work
I think it is right to remove it.

**Comment by jsmeix** [comment]
@pcahyna 
I dared to assign it to you because it seems
you know at least something about that area.
Feel free to merge it when it is OK for you.

**Comment by pcahyna** [comment]
@jsmeix no problem! I think the only question is whether the non-functional `.travis.yml` should be removed or should be left in the tree (with a comment, perhaps) - the latter would make it easier to resurrect Travis testing in the future if anyone is interested. (Whether anyone would be interested in this is another question, given the availability of probably superior alternatives.)

**Comment by hpannenb** [comment]
@pcahyna I think leaving `.travis.yml` will be a good approach. I just recognised this configuration file in my yesterday's excursion.

**Comment by pcahyna** [comment]
@hpannenb ok, I then suggest that you replace the commit that removes the file by a commit that adds a comment saying that it is currently broken and why.

**Comment by hpannenb** [comment]
Will create a new one.

**Comment by jsmeix** [comment]
This one is obsolete.

**Pull request closed without merging**
