### PR TITLE
Add alternative for 'poweroff.com' ('poweroff.c32' on RHEL8)

### PR DESCRIPTION
**Pull request by rmetrich**
#### Relax-and-Recover (ReaR) Pull Request Template

* Type: **Enhancement**

* Impact: **Low**

* Reference to related issue (URL):

* How was this pull request tested? Tested on RHEL7 (poweroff.com) and RHEL8 (poweroff.c32)

* Brief description of the changes in this pull request:

RHEL8 (syslinux-6.04) is shipping `poweroff.c32`, not `poweroff.com`.

### CODE REVIEW

**Comment by jsmeix** [comment]
Meanwhile I found the "Hide whitespace changes" check box
so that I could review the actual changes and they (still) look good to me.

**Comment by jsmeix** [comment]
As a side note:
The GitHub web interface has a bug.
It showed my first review message two times
but I cannot delete one so I edited the second one to nothing
and now both are gone.

**Comment by rmetrich** [comment]
> As a side note:
> The GitHub web interface has a bug.
> It showed my first review message two times
> but I cannot delete one so I edited the second one to nothing
> and now both are gone.

Just check latest commit:
https://github.com/rear/rear/pull/2238/commits/d2be687c4845ecf17bfdf03f7dc22103f0f27561

**Comment by gdha** [comment]
@rmetrich We think this PR is ready to be merged.

**Pull request merged**
