### PR TITLE
Split restoreonly workflow from recover workflow

### PR DESCRIPTION
**Pull request by jsmeix**
Now there is a new restoreonly workflow
that is a part of the (unchanged) recover workflow
namely the part that does only restore a backup,
see https://github.com/rear/rear/issues/987
which is a prerequirement for
https://github.com/rear/rear/issues/1088
"support multiple backups".

### CODE REVIEW

**Comment by jsmeix** [comment]
If there are no furious objections I will merge it soon.

I tested that usual "rear mkbackup" and "rear recover"
still work (at least for me).

**Comment by gdha** [comment]
@jsmeix only merge it when you are 100% sure it won't break the **recover** workflow.

**Comment by jsmeix** [comment]
There are two additional other workflows that are
other parts of the (unchanged) recover workflow:
layoutonly: recreate only the disk layout
finalizeonly: only finalize the recovery

For me 'layoutonly' folowed by 'restoreonly' seemd to work
but the final 'finalizeonly' failed to install the bootloader.
I.e. currently the recover workflow is not yet correctly
split into separated sub-workflows.

What works for me is 'recover' which restores an initial
backup of the basic system and installs the bootloader
followed by 'restoreonly' that restores an additional backup.

One must use the new '-C' option to specify the right
config files for 'recover' versus 'restoreonly'.

Here an example that had worked for me:
<pre>
d25:~/rear # grep -v '^#' etc/rear/local.conf

OUTPUT=ISO
SSH_ROOT_PASSWORD="rear"
USE_DHCLIENT="yes"

d25:~/rear # grep -v '^#' etc/rear/base.conf  

this_file_name=$( basename ${BASH_SOURCE[0]} )
LOGFILE="$LOG_DIR/rear-$HOSTNAME-$WORKFLOW-${this_file_name%.*}.log"
BACKUP_PROG_EXCLUDE=( /root/* /home/* )
BACKUP_PROG_ARCHIVE="backup-${this_file_name%.*}"
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://10.160.4.244/nfs

d25:~/rear # grep -v '^#' etc/rear/rest.conf 

this_file_name=$( basename ${BASH_SOURCE[0]} )
LOGFILE="$LOG_DIR/rear-$HOSTNAME-$WORKFLOW-${this_file_name%.*}.log"
BACKUP_ONLY_INCLUDE="yes"
BACKUP_PROG_INCLUDE=( /root/* /home/* )
BACKUP_PROG_ARCHIVE="backup-${this_file_name%.*}"
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://10.160.4.244/nfs

d25:~/rear # usr/sbin/rear -C base -d -D mkbackup

Relax-and-Recover 1.19 / Git
Using log file: /root/rear/var/log/rear/rear-d25.log
Sourcing additional configuration file '/root/rear/etc/rear/base.conf'
Using backup archive 'backup-base.tar.gz'
Creating disk layout
Creating root filesystem layout
Copying logfile /root/rear/var/log/rear/rear-d25.log into initramfs as '/tmp/rear-d25-mkbackup-base-partial-2016-11-29T16:17:38+01:00.log'
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Creating initramfs
Making ISO image
Wrote ISO image: /root/rear/var/lib/rear/output/rear-d25.iso (150M)
Copying resulting files to nfs location
Saving /root/rear/var/log/rear/rear-d25.log as rear-d25-mkbackup-base.log to network output location
Creating tar archive '/tmp/rear.5HVHqErloTlXdAE/outputfs/d25/backup-base.tar.gz'
Archived 1249 MiB [avg 8647 KiB/sec] OK
Archived 1249 MiB in 149 seconds [avg 8589 KiB/sec]
Saving /root/rear/var/log/rear/rear-d25.log as /root/rear/var/log/rear/rear-d25-mkbackup-base.log

d25:~/rear # usr/sbin/rear -C rest -d -D mkbackuponly

Relax-and-Recover 1.19 / Git
Using log file: /root/rear/var/log/rear/rear-d25.log
Sourcing additional configuration file '/root/rear/etc/rear/rest.conf'
Using backup archive 'backup-rest.tar.gz'
Creating disk layout
Creating tar archive '/tmp/rear.5UTB72OsoKkZkEB/outputfs/d25/backup-rest.tar.gz'
Archived 158 MiB [avg 23257 KiB/sec] OK
Archived 158 MiB in 8 seconds [avg 20350 KiB/sec]
Saving /root/rear/var/log/rear/rear-d25.log as /root/rear/var/log/rear/rear-d25-mkbackuponly-rest.log
</pre>

That results on the NFS server those files:
<pre>
README
VERSION
backup-base.log
backup-base.tar.gz
backup-rest.log
backup-rest.tar.gz
rear-d25-mkbackup-base.log
rear-d25.iso
</pre>
The var/log/rear/rear-d25-mkbackuponly-rest.log
is curently not yet copied to the NFS server.

The recovery looks like this:
<pre>
RESCUE d25:~ # rear -C base -d -D recover

Relax-and-Recover 1.19 / Git
Using log file: /var/log/rear/rear-d25.log
Sourcing additional configuration file '/etc/rear/base.conf'
Running workflow recover within the ReaR rescue/recovery system
Starting required daemons for NFS: RPC portmapper (portmap or rpcbind) and rpc.statd if available.
Started RPC portmapper 'rpcbind'.
RPC portmapper 'rpcbind' available.
Started rpc.statd.
RPC status rpc.statd available.
Using backup archive 'backup-base.tar.gz'
NOTICE: Will do driver migration
Calculating backup archive size
Backup archive size is 1.3G     /tmp/rear.AXfryZMO4qR9DI4/outputfs/d25/backup-base.tar.gz (compressed)
Comparing disks.
Disk configuration is identical, proceeding with restore.
Start system layout restoration.
Creating partitions for disk /dev/sda (msdos)
Creating filesystem of type ext4 with mount point / on /dev/sda2.
Mounting filesystem /
Creating swap on /dev/sda1
Disk layout created.
Restoring from '/tmp/rear.AXfryZMO4qR9DI4/outputfs/d25/backup-base.tar.gz'...
Restored 2704 MiB [avg 76936 KiB/sec] OK
Restored 2704 MiB in 37 seconds [avg 74857 KiB/sec]
Restoring finished.
Restore the Mountpoints (with permissions) from /var/lib/rear/recovery/mountpoint_permissions
Installing GRUB2 boot loader
Finished recovering your system. You can explore it under '/mnt/local'.
Saving /var/log/rear/rear-d25.log as /var/log/rear/rear-d25-recover-base.log

RESCUE d25:~ # rear -C rest -d -D restoreonly
Relax-and-Recover 1.19 / Git
Using log file: /var/log/rear/rear-d25.log
Sourcing additional configuration file '/etc/rear/rest.conf'
Running workflow restoreonly within the ReaR rescue/recovery system
Starting required daemons for NFS: RPC portmapper (portmap or rpcbind) and rpc.statd if available.
Started RPC portmapper 'rpcbind'.
RPC portmapper 'rpcbind' available.
RPC status rpc.statd available.
Using backup archive 'backup-rest.tar.gz'
NOTICE: Will do driver migration
Calculating backup archive size
Backup archive size is 160M     /tmp/rear.XRRC8EHMewgstLn/outputfs/d25/backup-rest.tar.gz (compressed)
Restoring from '/tmp/rear.XRRC8EHMewgstLn/outputfs/d25/backup-rest.tar.gz'...
Restored 34 MiB [avg 17415 KiB/sec] OK
Restored 34 MiB in 3 seconds [avg 11610 KiB/sec]
Restoring finished.
Restore the Mountpoints (with permissions) from /var/lib/rear/recovery/mountpoint_permissions
Finished recovering your system. You can explore it under '/mnt/local'.
Saving /var/log/rear/rear-d25.log as /var/log/rear/rear-d25-restoreonly-rest.log

RESCUE d25:~ # reboot
umounting all filesystems
...
syncing disks... waiting 3 seconds before reboot
</pre>

**Comment by jsmeix** [comment]
@gdha 
I cannot be 100% sure because I cannot test all and everything.

I really tried hard to implement all in an only-additional way
(i.e. without changing any current behaviour).

But I am not a 100% perfect machine ;-)

**Comment by gdha** [comment]
@jsmeix sure understood (nobody is prefect ;) 
Do I understand it correctly that the _restoreonly_ is only useful when we had a previous _mkbackuponly_?

**Comment by jsmeix** [comment]
Normally one or more restoreonly would match
one or more previous mkbackuponly when it is used
as I did above (i.e. for multiple backups).

But I intend that restoreonly should also be useful
when it is used as described in
https://github.com/rear/rear/issues/987
i.e. to recover a system from soft errors
(like deleting all of /lib/) or in general when
the disk layout is not damaged but one cannot
restore the backup from within the running system.

**Comment by jsmeix** [comment]
The current restoreonly workflow does not yet work
for the usecase as described in
https://github.com/rear/rear/issues/987
because currently there is nothing mounted
at /mnt/local.
With manual mounting the right stuff at /mnt/local before
the restoreonly workflow seems to work for me:
<pre>
f231:~ # rm -rf /lib*

f231:~ # cat /etc/rear/local.conf
-bash: /usr/bin/cat: No such file or directory

f231:~ # reboot
-bash: /sbin/reboot: No such file or directory

f231:~ # init 6
-bash: /sbin/init: No such file or directory

I did a hard power off switch and
booted the local "Relax-andRecover" GRUB entry
then in the recovery system I did:

RESCUE f231:~ # mount /dev/sda2 /mnt/local
RESCUE f231:~ # 
RESCUE f231:~ # mount | grep sd
/dev/sda2 on /mnt/local type ext4 (rw,relatime,data=ordered)
RESCUE f231:~ # 
RESCUE f231:~ # rear -d -D restoreonly
Relax-and-Recover 1.19 / Git
Using log file: /var/log/rear/rear-f231.log
Running workflow restoreonly within the ReaR rescue/recovery system
Starting required daemons for NFS: RPC portmapper (portmap or rpcbind) and rpc.statd if available.
Started RPC portmapper 'rpcbind'.
RPC portmapper 'rpcbind' available.
Started rpc.statd.
RPC status rpc.statd available.
Using backup archive 'backup.tar.gz'
NOTICE: Will do driver migration
Calculating backup archive size
Backup archive size is 1.2G     /tmp/rear.VSrN7cjHqW8Hggh/outputfs/f231/backup.tar.gz (compressed)
Restoring from '/tmp/rear.VSrN7cjHqW8Hggh/outputfs/f231/backup.tar.gz'...
Restored 2406 MiB [avg 60097 KiB/sec] OK
Restored 2406 MiB in 42 seconds [avg 58666 KiB/sec]
Restoring finished.
Restore the Mountpoints (with permissions) from /var/lib/rear/recovery/mountpoint_permissions
Finished recovering your system. You can explore it under '/mnt/local'.

RESCUE f231:~ # find /mnt/local/lib* | wc -l
4131

RESCUE f231:~ # reboot
umounting all filesystems
...

I booted the original system entry in GRUB
and I am back to normal operation:

f231:~ # mount | grep sda
/dev/sda2 on / type ext4 (rw,relatime,data=ordered)

f231:~ # grep -v '^#' /etc/rear/local.conf
OUTPUT=ISO
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://10.160.4.244/nfs
SSH_ROOT_PASSWORD="rear"
USE_DHCLIENT="yes"
KEEP_BUILD_DIR=""
GRUB_RESCUE="yes"
</pre>

**Comment by jsmeix** [comment]
Slept over it for one night,
still no dark foreboding,
I think I merge it today.

Of course its current state is only an initial step
but I think it is a first step into the right direction
that should be in GitHub master code so that also
others can easily try it out and report shortcomings
or even regressions that I overlooked so that I could
get things fixed before the official ReaR 2.0 release.

**Comment by jsmeix** [comment]
Regarding
https://github.com/rear/rear/pull/1091#issuecomment-263638707

The current restoreonly workflow implements
only what its name tells (strictly speaking)
Currently it only restores - nothing more.

I.e. the current restoreonly workflow does not implement
https://github.com/rear/rear/issues/987

**Pull request merged**
