### PR TITLE
Add nano, dhcp client, sshd start to bash history

### PR DESCRIPTION
**Pull request by ProBackup-nl**
Some handy command the help me getting (debug) things done, in the Rear recovery environment.

### CODE REVIEW

**Comment by gdha** [comment]
@ProBackup-nl No objections against it - so I approve/accept it

**Comment by ProBackup-nl** [comment]
@jsmeix 
Due to comment:

> # -----------------------------------------------------80-|

I though the convention here, is to make comments that fit within 80 characters. That is why I didn't left align them. Should the 80 character rule(r) comment be kept or removed?

**Comment by jsmeix** [comment]
I think that comment is more a hint that a strict rule
because ist string length is 60 characters.
Some characters are needed for the bash prompt
in the recovery system but I think the current is still o.k.
And even if it exceeds what fits on a line on a small terminal
it is only a cosmetic issue.

**Comment by jsmeix** [comment]
This pull request is somehow related to
https://github.com/rear/rear/issues/1298

**Pull request merged**
