### PR TITLE
Let 'dd' read and write up to 1M=1024*1024 bytes at a time to speed up things

### PR DESCRIPTION
**Pull request by jsmeix**
* Type: **Enhancement**

* Impact: **Normal**

* Reference to related issue (URL):
https://github.com/rear/rear/issues/2369
and
https://github.com/rear/rear/issues/2458

* How was this pull request tested?
Tested by @dsamx in https://github.com/rear/rear/issues/2458

* Brief description of the changes in this pull request:
Let 'dd' read and write up to 1M=1024*1024 bytes at a time to speed up things

### CODE REVIEW

**Comment by gozora** [comment]
Hello @jsmeix,

You can add `bs` option there, no problem with that.

V>

**Comment by jsmeix** [comment]
@gozora 
I also found analogous code in restore/BLOCKCLONE/default/400_restore_clone.sh
where I also added `bs=1M`.

But there is a possible issue when e.g.
`BLOCKCLONE_PROG_OPTS="bs=4k"` is set by the user, cf. 
https://github.com/rear/rear/blob/master/doc/user-guide/12-BLOCKCLONE.adoc

Please double check
https://github.com/rear/rear/pull/2459/commits/dcdc026b72b3d2cb8bd9449bd346d1016a8cc753
and
https://github.com/rear/rear/pull/2459/commits/88c71642a7c8c86cfb3411b4482004c6bd8745d5
if I did things right.

**Comment by gozora** [comment]
@jsmeix yes it is fine, since `dd` picks last option specified, `BLOCKCLONE_PROG_OPT` will be able to override hard-coded value and user will have the final word.

V.

**Comment by jsmeix** [comment]
@gozora 
thank you for your review!

**Pull request merged**
