### PR TITLE
Replace AUTHORS by MAINTAINERS file and explain more background info

### LINKED ISSUE #1427: Align AUTHORS and COPYRIGHT persons in various sources
In
https://github.com/rear/rear/commit/fd13be8f1bb091e1d324d35d3be527b34346a38e
I noticed changes of the AUTHORS and COPYRIGHT parts
in doc/rear.8.adoc.

Those changes are missing
in doc/rear.8 and
in usr/sbin/rear and
in the AUTHORS file.

I can adapt those files but I would need to know
what the actually right list of authors is.

### PR DESCRIPTION
**Pull request by schlomo**
about the many contributors who helped ReaR. Fixes #1427 

For minor changes please simply push to this branch. For bigger ones let me know and I'll do the work.

I'll ask everybody to review. If I don't hear from you within a couple of days/weeks then I assume that you consent to this change.

### CODE REVIEW

**Comment by jsmeix** [comment]
I wonder if it is legally (i.e. according to the GPL)
sufficient to have the authors and contributors
(I think in GPL wording all relevant contributors
are legally same as authors) only mentioned indirectly
via an external link as in
<pre>
To see the full list of authors and their contributions please look at
https://github.com/rear/rear/graphs/contributors
</pre>

Perhaps we must provide a list of the authors in a source file?
Perhaps we can leave out the e-mail addresses of the authors?

Or does a git repository count as sources for the GPL?
I.e. what one gets via
<pre>
git clone https://github.com/rear/rear.git
</pre>
because that contains all authors and their contributions
in the git log - but a special tool 'git' is needed here
to "pull out" the authors and their contributions.

**Comment by schlomo** [comment]
@jsmeix I share your concern. It seems that the FSF serves as some kind of a copyright proxy (https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html), but the process seems quite cumbersome on first reading. Can you maybe ask the specialists at SUSE for some practical advise?

**Comment by jsmeix** [comment]
@schlomo 
I will ask them but from my (outsider) experience
often a lawyer cannot provide concrete practical advise
because (as far as I understand it) license issues are
often complicated without matching court decisions
so that often "it depends..."

**Comment by jsmeix** [comment]
The currently proposed MAINTAINERS file
https://github.com/rear/rear/blob/93e544a258ff184d09b94a5c7128380a488b3227/MAINTAINERS
lists Dag Wieers and Jeroen Hoekx
but as far as I see they do no longer actively maintain ReaR.

I think the MAINTAINERS file is meant to list
those who currently actively maintain ReaR.

I think a MAINTAINERS file is not meant to list all
contributors which is what an AUTHORS file is meant to do.

Accordingly I think when Dag Wieers and Jeroen Hoekx
really do no longer actively maintain ReaR, then they
should no longer be not listed in the MAINTAINERS file.

Alternatively the MAINTAINERS file could have separated
sections to distinguish currently active maintainers
from no longer active maintainers.

E.g. something as the "Alumni" section in the exhaustive and explanatory
https://raw.githubusercontent.com/moby/moby/master/MAINTAINERS
but probably much shorter for what ReaR actually needs.

**Comment by schlomo** [comment]
I'll ask them

**Comment by dagwieers** [comment]
BTW I noticed that I still have merge rights on this repository. This probably dates back from the time we moved to Github. (Which I think was the best decision we could have made ;-))

You may want to restrict my "write" access (and probably @jhoekx too) for security purposes. It would still be nice to stay as a member of the project though.

And when there is a need to have commit/merge rights again, I'm sure we can enable it again at that time.

**Comment by schlomo** [comment]
@jsmeix I know that this is not perfect, I hope that this is a step into the right direction.

**Comment by jsmeix** [comment]
@schlomo 
for me it is "sufficiently perfect" :+1: cf.
https://github.com/rear/rear/pull/1429#pullrequestreview-52004087
Many thanks for it!

**Pull request merged**
