### PR TITLE
WIP: ReaR 2.8 release preparations

### PR DESCRIPTION
**Pull request by jsmeix**
See https://github.com/rear/rear/wiki/Release-process#preparation

Done:

* rear.8.adoc : Update version number and release date

* usr/sbin/rear : Update VERSION and RELEASE_DATE

* packaging/rpm/rear.spec : Update Version

* packaging/debian/changelog : Add changelog entries

* packaging/debian/rear.dsc : Update Version

WIP (perhaps for tomorrow):

* doc/rear-release-notes.txt related things

### CODE REVIEW

**Comment by gdha** [comment]
@jsmeix All is fine for me - happy release!

**Comment by jsmeix** [comment]
Via the last two commits I replaced
the old doc/rear-release-notes.txt
by a completely new one to finally solve
https://github.com/rear/rear/issues/3302

**Comment by gdha** [comment]
@jsmeix Could you please correct some misspelled words before the actual release?
```bash
Error: ./doc/rear-release-notes.txt:688: clude ==> clued, clue
Error: ./doc/rear-release-notes.txt:799: accomodating ==> accommodating
Error: ./doc/rear-release-notes.txt:1007: avod ==> avoid
Error: ./doc/rear-release-notes.txt:1184: belogs ==> belongs
Error: ./doc/rear-release-notes.txt:1191: specifiy ==> specify
Error: ./doc/rear-release-notes.txt:1[27](https://github.com/rear/rear/actions/runs/12410085401/job/34644976651?pr=3370#step:6:28)4: enfore ==> enforce
Error: ./doc/rear-release-notes.txt:1493: configuation ==> configuration
Error: ./doc/rear-release-notes.txt:1539: exlude ==> exclude, exude
Error: ./doc/rear-release-notes.txt:1627: incresed ==> increased
Error: ./doc/rear-release-notes.txt:1654: Previosly ==> Previously
Error: ./doc/rear-release-notes.txt:1654: possitions ==> positions
Error: ./doc/rear-release-notes.txt:1751: tha ==> than, that, the
Error: ./doc/rear-release-notes.txt:2046: interactiv ==> interactive
Error: ./doc/rear-release-notes.txt:2048: characte ==> character
```

**Comment by jsmeix** [comment]
In the new one
https://github.com/rear/rear/blob/jsmeix-rear28-preparations/doc/rear-release-notes.txt
the line breaks are sometimes not very good
(but the content is at least readable).
I created it as described in
https://github.com/rear/rear.github.com/blob/master/README.md
via
```
export LC_ALL=POSIX
export LANG=POSIX
lynx --dump https://relax-and-recover.org/documentation/release-notes-2-8 >rear-release-notes.txt
```
So I leave it as is.

**Comment by jsmeix** [comment]
@gdha 
thank you for review.
I will fix the misspelled words in
https://github.com/rear/rear.github.com/blob/master/documentation/release-notes-2-8.md
and re-generate doc/rear-release-notes.txt from it.

**Review by gdha — APPROVED** [review]

**Comment by pcahyna** [comment]
> @jsmeix I'm sorry, please generate the text release notes as you see fit.
> 
> If the text release notes file makes so much work, maybe we can get rid of it or simply have a one-liner pointing to the home page? Less effort and good enough? I'm not sure if so many users actually only can read the release notes when it is shipped with the ReaR package itself.

Or just use the original file in markdown format?

**Comment by jsmeix** [comment]
```
lynx -dont_wrap_pre --dump https://relax-and-recover.org/documentation/release-notes-2-8 >rear-release-notes.txt
```
improves things - at least in the git commit messages.
Now the `tha` `interactiv` `characte` issues are gone.

But '-dont_wrap_pre' still results "strange" line breaks
in normal text, e.g.
```
     * New portable mode --portable and OUTPUT=PORTABLE, see
       [23]https://github.com/rear/rear/blob/master/doc/user-guide/17-Port
       able-Mode.adoc for more information.
```
where the long URL gets wrapped within the word "Portable".

**Comment by jsmeix** [comment]
Allow lines up to 100 characters helps a lot
to avoid ugly looking line breaks:
```
lynx -dont_wrap_pre -width=100 --dump https://relax-and-recover.org/documentation/release-notes-2-8 >rear-release-notes.txt
```

**Comment by jsmeix** [comment]
The updated
https://github.com/rear/rear/blob/jsmeix-rear28-preparations/doc/rear-release-notes.txt
looks rather good to me.

**Comment by jsmeix** [comment]
@rear/contributors 
I will merge this pull request very soon
to be able to do "the actual release" today
(I must leave at 14:00 today because of an appointment).

**Comment by jsmeix** [comment]
Latest commit updates rear-release-notes.txt
with the latest ReaR 2.8 commit messages from
https://github.com/rear/rear.github.com/commit/7477f38d929b128cdc6977cb99da9cca54e29d30

**Comment by jsmeix** [comment]
The failing "Codespell / codespell" check is now
https://github.com/rear/rear/actions/runs/12411610323/job/34649664834?pr=3370
only because of
```
Error: ./doc/rear-release-notes.txt:660: clude ==> clued, clue
```
which is false alarm, see
https://github.com/rear/rear/pull/3370#issuecomment-2553318705

**Comment by jsmeix** [comment]
All checks are successful
except "Codespell / codespell" which is false alarm.
So I merge it now.

**Pull request merged**
