### PR TITLE
Typo in install_yaboot.sh with sfdisk command (2>&8 instead of 2>&1) ????

### PR DESCRIPTION
**Pull request by schabrolles**
I'm not sure, but it looks like a typo. Could you check and confirm ?

### CODE REVIEW

**Comment by schabrolles** [comment]
After looking at other rear shell, I've seen other references to file descriptor 8 and 7. So I think it is not a typo .... but I prefer asking you for confirmation.
Could you tell me why we are using those fd ?
thanks.

**Comment by gdha** [comment]
@schabrolles in `conf/default.conf` you will find some info:
````
# NOTE: This command will be run within the ProgressBar system !! You should therefore avoid
# output on STDOUT by rerouting that to FD 8, the progress bar
EXTERNAL_CHECK="ssh vms date >&8"
````
The use of the progress bar is however not used anymore these days.

**Comment by gdha** [comment]
@schlomo What shall we do with the progress bar thingy?

**Comment by schlomo** [comment]
If we don't use the progress bar any more then we should also remove all references to FD8, e.g. `>&8`. The progress bar mechanism would swallow all data.

**Comment by jsmeix** [comment]
There is currently the generic question whereto
stdout and stderr output should go, see https://github.com/rear/rear/issues/885

In particular see https://github.com/rear/rear/issues/885#issuecomment-226784037 (excerpt):
<pre>
the mkfs commands do not have >&2 appended (I guess that was done on purpose so that the user see something on the screen).
</pre>

Therefore there is also the question here if the sfdisk output
should tray on stderr or if it should be redirected to stdout
"on purpose so that the user see something on the screen"?

Regardless of that question we do no longer use FD8
so that either "2>&1" or nothing is correct nowadays.

@schabrolles 
by the way:
Preferably use $( COMMAND ) instead of backticks,
see https://github.com/rear/rear/wiki/Coding-Style

**Comment by schabrolles** [comment]
@jsmeix 
I'm not the original author and also noticed that ... I can add this change to also remove backticks.

**Pull request merged**
