### PR TITLE
Small linguistic fix

### PR DESCRIPTION
**Pull request by jpmens**
#### Relax-and-Recover (ReaR) Pull Request Template

Please fill in the following items before submitting a new pull request:

##### Pull Request Details:

* Type:  **Other**

* Impact: **Low**

* Reference to related issue (URL): 

none

* How was this pull request tested?

it wasn't

* Brief description of the changes in this pull request:

While it also was `was` when it's been done, `was` looks strange when it's to be done. Get it? :-)

### CODE REVIEW

**Comment by jsmeix** [comment]
Also in doc/rear.8.adoc there fixed via
https://github.com/rear/rear/commit/0b6870783545865094394e15203c8a83381332cf
and in doc/rear.8 there fixed via
https://github.com/rear/rear/commit/2150fb1a56cb2508d78a670e905215dab58fd2cb

**Comment by jsmeix** [comment]
@jpmens 
thank you for your careful reading of our documentation.
We appreciate corrections of even small spelling errors
because spelling errors could make the whole thing look a bit sloppy like:
"When they can't even spell right how could they ever make right code?" ;-)

**Comment by gdha** [comment]
@jsmeix Now I understand why we have some bugs in our code - it was just miss-spelled ;-)

**Comment by jsmeix** [comment]
@gdha 
:-)
now I am thinking about an appropriate place in our documentation
for some humor like
```
We do not have actual bugs in our code.
If some code does not work it is just accidentally misspelled.
We try our best but unfortunately none of us is bash native speaker.
```
;-)

**Comment by jpmens** [comment]
PR for the bottom of `rear.8`:

```
.SH "BUGS"
.sp
We do not have actual \fIbugs\fR in our code.
If some code does not work, it is just \fIaccidentally misspelled\fR.
We do \fBour best\fR but unfortunately none of us is \fInative bash speaker\fR.
```

:-)

**Comment by pcahyna** [comment]
and there should not be a comma before "how" ...

**Comment by jsmeix** [comment]
Removed comma via
https://github.com/rear/rear/commit/ef074a6041ebb640b258dd36e4f8dbf3bf0e72fe

@pcahyna 
thank you for proofreading!

**Pull request merged**
