### PR TITLE
conf: reintroduce `Linux-s390.conf`

### PR DESCRIPTION
**Pull request by lzaoral**
#### Relax-and-Recover (ReaR) Pull Request Template

Please fill in the following items before submitting a new pull request:

##### Pull Request Details:

* Type: **Bug Fix** / **Enhancement**

* Impact: **Normal**

* Reference to related issue (URL): https://github.com/rear/rear/issues/3144

* How was this pull request tested? Recovery of RHEL 9 in z/VM

* Description of the changes in this pull request:

The `conf` directory is the expected location for architecture-specific settings. Moreover, the `305_include_s390_tools.sh` script contained a potentially harmful check that could result in all s390/s390x tools being omitted from the recovery image with disastrous results.

Fixes: cba3590b27bedb526e5b439cd8d4d01e1ec0169a ("pull #2142") \
Resolves: #3144

### CODE REVIEW

**Comment by pcahyna** [comment]
@lzaoral I don't think you need to do a complete review of all the tools here - your code matches what used to exist before (except for the SELinux tools, which I suppose are included elsewhere), so it should be ok. But if you want to do this review at the same time, the tools are used at https://github.com/rear/rear/blob/0fa49b3089ad0015f1ab67335c596fc28066f2df/usr/share/rear/rescue/GNU/Linux/310_network_devices.sh#L29 and https://github.com/rear/rear/tree/0fa49b3089ad0015f1ab67335c596fc28066f2df/usr/share/rear/layout/prepare/Linux-s390 (although most of their use at the latter happens only if there actually is a DASD, so when we add support for SCSI disks, it won't be needed in case you have no DASDs, the `lsdasd` use is an exception and could be actually made conditional, as it is purely informative). The use in the former also does not seem to happen if `"$OS_MASTER_VENDOR" = "SUSE_LINUX"`.

**Comment by gdha** [comment]
@lzaoral is the removed `usr/share/rear/prep/Linux-s390/305_include_s390_tools.sh` really completely obsolete?

**Comment by pcahyna** [comment]
@gdha why shouldn't it be? The variable settings are obsoleted by the new conf file and the check should not be there, as explained in #3144 . Do you have anything else in mind?

**Comment by gdha** [comment]
> @gdha why shouldn't it be? The variable settings are obsoleted by the new conf file and the check should not be there, as explained in #3144 . Do you have anything else in mind?

Not really - just being prudent.
I'm fine to remove that script.

**Review by gdha — APPROVED** [review]

**Review by pcahyna — APPROVED** [review]

**Comment by gdha** [comment]
@rear/contributors  When there are no objections we can perform a PR later this week?

**Comment by gdha** [comment]
PR #3281 merged into master

**Pull request merged**
