### PR TITLE
Some code simplification plus explicit 'return 0' where needed

### PR DESCRIPTION
**Pull request by jsmeix**
Some simplification in code that is related to issue 1541
plus explicit 'return 0' when return is intended after
a failed command i.e. when return is actually 'success'
because otherwise return results the exit code of the
failed command e.g. as in
<pre>
# function testfunc1 () { test -f qqq || return ; }
# testfunc1
# echo $?
1

# function testfunc2 () { grep -Q foo bar && echo found ; return ; }
# testfunc2
grep: invalid option -- 'Q'
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
# echo $?
2
</pre>

### CODE REVIEW

**Comment by jsmeix** [comment]
@gdha 
in usr/share/rear/prep/GNU/Linux/300_include_grub_tools.sh
I added a 'FIXME for you because via
https://github.com/rear/rear/commit/2de5b1b9f3f1cc6e59da860bfa91d391790fe82c
you added
<pre>
grubdir=$(ls -d /boot/grub*)
</pre>
which is not fail-safe because
usr/sbin/rear sets 'shopt -s nullglob'
so that the 'ls' command will list all files in the current
working directory if nothing matches the bash globbing
pattern '/boot/grub*' which results in this case '.' in 'grubdir'
(the plain 'ls -d' output in the current working directory).

**Comment by jsmeix** [comment]
@gdha 
do you have a good idea how one could make things like
<pre>
grubdir=$( ls -d /boot/grub* )
</pre>
work fail-safe even with  'shopt -s nullglob'?

I would like it get the 'FIXME' fixed.

**Comment by jsmeix** [comment]
I think I found another possible way
how to be fail-safe for 'shopt -s nullglob':

Do not use
<pre>
ls globbing_pattern
</pre>
but (where possible)
<pre>
echo -n globbing_pattern
</pre>
because with 'shopt -s nullglob' the 'echo -n' command
outputs nothing if nothing matches the globbing pattern
so that one can test for an empty variable like:
<pre>
local grubdir="$( echo -n /boot/grub* )"
# Set fallback if nothing matches '/boot/grub*'
test -d "$grubdir" || grubdir='/boot/grub'
</pre>

I implemented that in
https://github.com/rear/rear/pull/1542/commits/6ee5c6d9c98ca49eb58001ea39073ab4ff62bd5c

**Comment by gdha** [comment]
@jsmeix excellent work - thank you for that

**Comment by jsmeix** [comment]
In a ReaR git checkout directory I did things like
<pre>
# find usr/sbin/rear usr/share/rear/ | xargs grep '=$(ls '

# find usr/sbin/rear usr/share/rear/ | xargs grep '=$( ls '

# find usr/sbin/rear usr/share/rear/ | xargs grep '="$(ls '

# find usr/sbin/rear usr/share/rear/ | xargs grep '="$( ls '
</pre>
and found
<pre>
var=$( ls globbing_pattern )
</pre>
usage that needs to be fixed only in
output/ISO/Linux-i386/810_prepare_multiple_iso.sh

Other such usage in
lib/bootloader-functions.sh
and
output/USB/Linux-i386/300_create_extlinux.sh
looks to be already prepared for 'shopt -s nullglob'
so that I only added an explanatory comment there.

See
https://github.com/rear/rear/pull/1542/commits/5dac6f84c27254208b9134318823496e9a763090

**Comment by jsmeix** [comment]
Because all still works for me I "just merge" it, cf.
https://github.com/rear/rear/issues/1545#issuecomment-339352069

**Pull request merged**
