### PR TITLE
Ignore relabeling of /boot/efi only if directory exists.

### PR DESCRIPTION
**Pull request by gozora**
##### Pull Request Details:

* Type: **Enhancement**

* Impact: **Low**

* Reference to related issue (URL): https://github.com/rear/rear/issues/1972

* How was this pull request tested?
By running `rear recover` on Arch Linux.

* Brief description of the changes in this pull request:
This patch avoids `rear recover` to end with error if /boot/efi directory does not exist in late recover stage (archive is already restored), and instead adds /boot/efi to SElinux relabeling ignore list, only if /boot/efi directory exists.

### CODE REVIEW

**Comment by gozora** [comment]
After thinking about this PR for a while, I've decided for less invasive and IMHO more correct way ...

V.

**Comment by gozora** [comment]
Hello @jsmeix 

My knowledge of SELinux is limited to disabling of this feature ;-)

> (a)
> Do nothing when SELinux is not used.

I'm not sure if we can detect SELinux usage and mode of operation reliably across all distributions...

> Do not silently overwrite user's files.
Fully agree, Maybe using:
```
-  cat > $TARGET_FS_ROOT/etc/selinux/fixfiles_exclude_dirs <<EOF
+  cat >> $TARGET_FS_ROOT/etc/selinux/fixfiles_exclude_dirs <<EOF
...
```

Would be better ...

V.

**Comment by jsmeix** [comment]
@gdha 
I assigned you too here because I assume you could help
with the SELinux related questions here.

But there is no need to do the general clean up right now here.
We could also do it later in a separated step as time permits.

**Comment by jsmeix** [comment]
A proposal how to simplify and clean it up:
<pre>
# For UEFI only we should avoid SElinux relabeling vfat filesystem /boot/efi

# Skip if UEFI is not used:
is_true $USING_UEFI_BOOTLOADER || return 0

# Skip if there is no etc/selinux/ directory (e.g. when SELinux is not used)
# and if there is no etc/selinux/ directory creating a fixfiles_exclude_dirs
# file therein cannot work anyway:
test -d $TARGET_FS_ROOT/etc/selinux || return 0

# Skip if there is no boot/efi directory:
test -d $TARGET_FS_ROOT/boot/efi || return 0

# Do not overwrite an existing etc/selinux/fixfiles_exclude_dirs file
# An existing file is user data that was restored from the his backup and
# user data is sacrosanct unless the user would have confirmed otherwise:
if test -s $TARGET_FS_ROOT/etc/selinux/fixfiles_exclude_dirs ; then
    Log "Not overwriting the existing etc/selinux/fixfiles_exclude_dirs file"
    return 0
fi

# Create etc/selinux/fixfiles_exclude_dirs file from scratch:
cat &lt; $TARGET_FS_ROOT/etc/selinux/fixfiles_exclude_dirs &lt;&lt;EOF
/boot/efi
/boot/efi(/.*)?
EOF
</pre>

**Comment by gozora** [comment]
@jsmeix 
Nice one!
I'll update PR later today.
Thanks for your help!

V.

**Comment by jsmeix** [comment]
Using code to "Determine where the EFI System Prtition (ESP) is mounted" from
https://github.com/rear/rear/commit/14bfcd40d8d78ba6c45db11cbd31b2f83d0fb6c2
<pre>
# Determine where the EFI System Prtition (ESP) is mounted in the currently running recovery system:
esp_mountpoint=$( df -P "$TARGET_FS_ROOT/$UEFI_BOOTLOADER" | tail -1 | awk '{print $6}' )
# Use TARGET_FS_ROOT/boot/efi as fallback ESP mountpoint:
test "$esp_mountpoint" || esp_mountpoint="$TARGET_FS_ROOT/boot/efi"
</pre>
should sufficiently mitigate possible issues where ESP is mounted
also in this case here.

**Comment by gozora** [comment]
@jsmeix 
Just for a record, I guess you've meant:
```
-  cat < $TARGET_FS_ROOT/etc/selinux/fixfiles_exclude_dirs <<EOF
+  cat > $TARGET_FS_ROOT/etc/selinux/fixfiles_exclude_dirs <<EOF
$target_esp_mountpoint
$target_esp_mountpoint(/.*)?
EOF
```

V.

**Comment by jsmeix** [comment]
@gozora 
of course it must be
`cat > $TARGET_FS_ROOT/etc/selinux/fixfiles_exclude_dirs <<EOF`
(I fixed it in my comments above).

For the (not so) fun of it:
The reason for the typo was that I use `<pre> ... </pre>`
for preformatted text blocks but within `<pre> ... </pre>`
one cannot use `<` or '>' literally because they are reserverd HTML charaters
so that to display `<` or `>` one must use their HTML entities `&lt;` and `&gt;`
and I had accidentally used `&lt;` for `>` instead of `&gt;` but now I learned
that I can also use three backticks ` ``` ` and even how to display backticks
as backticks by having them in backticks plus leading and trailing spaces,
it's just so easy to simply write Markdown that even shows plain ASCII text
(braindead modern world)...

**Comment by gdha** [comment]
@schlomo are you fine with this PR?

**Comment by schlomo** [comment]
@gozora @gdha I cannot form an opinion as I am too far away from this problem.

Just wondering, if the `fixfiles_exclude_dirs` file exists and does not contain the ESP mount point, will the recovered system still work? Why not simply inject/append the ESP there?

**Comment by jsmeix** [comment]
Because this is only about to avoid SElinux relabeling the vfat filesystem of the ESP
my assumption was that it is "the right thing" to skip the actual action in that script
(which is creating etc/selinux/fixfiles_exclude_dirs file from scratch)
when any of the needed conditions is not met.

**Comment by gdha** [comment]
@gozora You can merge this PR from my point of view.

**Comment by rmetrich** [comment]
@gozora Sorry for the late wakeup, didn't see this until now, but adding /boot/efi to exclusion list is not needed at all. Internally, SELinux's `fixfiles` checks if the file system supports security labels, and VFAT doesn't, so it never tries to relabel `/boot/efi`.

**Comment by gozora** [comment]
Hello @rmetrich,

Reading https://github.com/rear/rear/issues/1972, this PR was mostly about correcting

```
if ! test -d "$TARGET_FS_ROOT/boot/efi" ; then
    Error "Could not find directory $TARGET_FS_ROOT/boot/efi"
fi
```
whew [510_selinux_fixfiles_exclude_dirs.sh](https://github.com/rear/rear/blob/master/usr/share/rear/restore/NETFS/Linux-i386/510_selinux_fixfiles_exclude_dirs.sh) runs.

_/boot/efi_ was part of `$TARGET_FS_ROOT/etc/selinux/fixfiles_exclude_dirs` even before this PR ...

But honestly I did not spent much time hacking SELinux, so if you think that _/boot/efi_ is not needed in this list, feel free to update the code ;-).

V.

**Pull request merged**
