### PR TITLE
Save and restore bash flags and options settings

### PR DESCRIPTION
**Pull request by jsmeix**
Implemented simple functions GetBashFlagsAndOptionsCommands
and ApplyBashFlagsAndOptionsCommands that are used
in a fail-safe way via an explicit variable that stores the
current bash flags and options commands and using
that explicit variable to re-apply them, i.e. like
<pre>
      saved_flags_options_cmds="$( GetBashFlagsAndOptionsCommands )"
      ... [change bash flags and options]
      ... [do something]
      ApplyBashFlagsAndOptionsCommands "$saved_flags_options_cmds"
</pre>
See https://github.com/rear/rear/issues/700

### CODE REVIEW

**Comment by jsmeix** [comment]
Oops!

This pull request has documentation stuff from my other pull request mixed in.

I will clode this broken pull request.

**Comment by schlomo** [comment]
Cool. Can you please use `small_letters_and_words_separated_by_underscore` function naming?

More consistent with the remaining ReaR code.

**Comment by jsmeix** [comment]
Oops2!

I used function names as in _input-output-functions.sh
but https://github.com/rear/rear/wiki/Coding-Style
makes it clear:
<pre>
Function names are lower case, words separated by underline (_)
</pre>

Now I wonder if - and if yes - how to distinguish function names
from variable names?

Globally used variables are uppercase (with words separated by underline '_') like SHARE_DIR DISKLAYOUT_FILE RECOVERY_FS_ROOT

Locally used varaiable should be lowercase and marked with "local" (also words separated by underline '_') like "local backup_path" or "local syslinux_modules_dir".

I think distinguishing functions from variables is obvious from the context how they are used so that both can have same syntax.

I wonder if we should distinguish globaly used functions from locally used functions by their naming syntax?

E.g. leading capitals for words in globally used functions like
<pre>
function Globally_Used_Function () {
    ...
}
</pre>
in contrast to
<pre>
function locally_used_function () {
    ...
}
.
.
.
locally_used_function ...
.
.
.
unset -f locally_used_function
</pre>

**Comment by schlomo** [comment]
Do we actually have a problem here? I would like to keep the rules to the absolue minimum...

**Comment by jsmeix** [comment]
I do not have a problem. I was only wondering and therefore I asked.

In https://github.com/rear/rear/pull/726 I use the function names get_bash_flags_and_options_commands and apply_bash_flags_and_options_commands

**Pull request closed without merging**
