### PR TITLE
Minor os-detection improvements

### PR DESCRIPTION
**Pull request by lzaoral**
#### Relax-and-Recover (ReaR) Pull Request Template

Please fill in the following items before submitting a new pull request:

##### Pull Request Details:

* Type: **Bug Fix** / **Enhancement** 
* Impact: **Normal**

* Reference to related issue (URL): See respective commit messages.

* Description of the changes in this pull request:
    * Set `OS_VENDOR` to `Arch_Linux` on Arch Linux
    * Remove incorrect check for `SUSE_LINUX`

edit: typo

### CODE REVIEW

**Review by jsmeix — APPROVED** [review]
I just approve it "bona fide"

**Comment by jsmeix** [comment]
@rear/contributors
provided there are no objections
I would like to merge it on Monday afternoon.

Or is this pull request (currently for ReaR 2.8)
not really needed for the ReaR 2.8 release
so that we could postpone it to ReaR 3.0?

But it is also labeled "bug" which indicates
it is needed for the ReaR 2.8 release.

**Comment by pcahyna** [comment]
Should we rename `usr/share/rear/lib/validated/Arch`? I have never used the validation stuff myself.

**Comment by schlomo** [comment]
Yes, good catch!! Users do send new things and I think that it is a cool feature that also gives us some personalised feedback

**Comment by pcahyna** [comment]
I mean change it to `Validation:  Arch_Linux/rolling/i386`

**Pull request merged**
