### PR TITLE
Separate PPC bootlist creation from bootloader installation

### PR DESCRIPTION
**Pull request by schabrolles**
Cleaning install PPC bootlist

- Separate PPC bootlist creation from bootloader installation. `creation of finalize/230_install_PPC_bootlist.sh`
  This allow to reduce the copy of scripts between different Arch/Distro.

- PPC bootlist is PowerVM specific (ppc64/ppc64le), but bootlader
  installation script can be shared with other Arch.

### CODE REVIEW

**Comment by jsmeix** [comment]
@schabrolles 
when you are working on
usr/share/rear/finalize/Linux-ppc64/200_install_yaboot.sh
could you perhaps also have a look at
usr/share/rear/finalize/SUSE_LINUX/ppc64/200_install_yaboot.sh
in particular regarding my 'FIXME:' comment therein?
Many thanks in advance!

Perhaps even SUSE_LINUX/ppc64/200_install_yaboot.sh
could be done in a more generic way?
Its name is 'install_yaboot' but actualy it calls '/sbin/lilo'?
I am not a PPC user but I guess PPC experts actually
understand what goes on behind the surface here ;-)

@gdha 
I added you as reviewer to be a bit more on the safe side.
Perhaps you even understand PPC booting?

**Comment by jsmeix** [comment]
@schabrolles 
many thanks for your more descriptive LogPrint message in
https://github.com/rear/rear/pull/1323/commits/9c455583a3e7b72fafb66e3a5ece2c5c4284790f
Regardless that I do not understand the details here,
it clearly helps PPC users to understand what goes on.

**Comment by schabrolles** [comment]
For your understanding ... in PowerVM (POWER HW virtualization) each VM (called LPAR: ligical Partition) can dynamically set the bootdevice boot order to the Hypervizor Firmware thanks to the command `bootlist`.

`bootlist` will translate logical name like `sda` to a uniq full path understandable by the hypervizor `/vdevice/vfc-client@3000000d/disk@500507680c21099f,0000000000000000:1,yaboot`

As it is closely linked to the adapter used, LUNid etc ... we need to regenerate bootlist when we restore to a new system (migration)

**Comment by schabrolles** [comment]
@jsmeix I've seen this FIXME, I think we should re-write the `install_yaboot.sh` for SLES ...; and may be renamed it `install_lilo.sh` ...

**Comment by jsmeix** [comment]
@schabrolles 
feel free to clean up the PPC booloader scipts as you like.
I appreciate it!

**Comment by jsmeix** [comment]
Luckily I am not a hypervisor so that I do not need to understand
/vdevice/vfc-client@3000000d/disk@500507680c21099f,0000000000000000:1,yaboot
;-)

**Comment by schabrolles** [comment]
Yes ;-) it is not really convenient, that's why we can thanks `bootlist` to make this translation for us :-)

I'll have a look and propose a new `210_install_lilo.sh` for SLES ppc64 and remove `200_install_yaboot.sh`

**Comment by schabrolles** [comment]
@gdha, 
- In SuSe, which uses `lilo` boot manager, PReP Boot partition is using a filesystem formatted in `vfat`=> `blkid` can detect this partition.
- In RHEL 6,   which uses `yaboot` boot manager, PReP Boot partition is RAW formatted => can't be detected by `blkid`

I would like to use "same kind" of script for `200_install_lilo.sh` and `210_install_yaboot.sh`... for an easier maintenance ...
There is no other reason :-) ... So, I'm open to other suggestion and feedback.

**Comment by schabrolles** [comment]
@gdha, @jsmeix  I've moved PPC bootlist to be run after bootloader creation.
I start changing numbering in finalize for issue #1331.

Can I use this branch to push the new numbering ? (because some files are changed or created in finalize in this branch, using the same branch will help to avoid conflict during merge.)

**Comment by gdha** [comment]
@schabrolles yes use the _master_ branch - the _dev_ branch has been deprecated for the moment

**Comment by schabrolles** [comment]
@gdha Ok, but I would say, can I use this thread (#1323) and make the changes in my remote branch `schabrolles:install_PPC_bootlist`

**Comment by schabrolles** [comment]
@gdha @jsmeix 
I made some adjustment regarding the numbering in finalize.

Here is what I get now:
```
Source finalize/default/010_prepare_checks.sh
Source finalize/default/100_populate_dev.sh
Source finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
Source finalize/GNU/Linux/250_migrate_lun_wwid.sh
Source finalize/GNU/Linux/260_rename_diskbyid.sh
Source finalize/GNU/Linux/280_migrate_uuid_tags.sh
Source finalize/GNU/Linux/300_create_mac_mapping.sh
Source finalize/GNU/Linux/310_migrate_udev_rules.sh
Source finalize/GNU/Linux/320_migrate_network_configuration_files.sh
Source finalize/GNU/Linux/430_create_multipath_config.sh
Source finalize/SUSE_LINUX/ppc64/550_rebuild_initramfs.sh
Source finalize/Linux-ppc64/600_install_yaboot.sh
Source finalize/Linux-ppc64/610_install_lilo.sh
Source finalize/Linux-ppc64/620_install_grub2.sh
Source finalize/Linux-ppc64/680_install_PPC_bootlist.sh
Source finalize/default/880_check_for_mount_by_id.sh
Source finalize/default/890_finish_checks.sh
Source finalize/default/900_remount_sync.sh
```

I also put a first draft for the readme:
```
000-099: initialization
100-199: creating devices on TARGET (/dev)
200-299: disk device migration
300-399: network device migration
400-499: Update some configuration on TARGET (like multipath)
500-599: rebuild initrd
600-699: bootloader installation
700-799:
800-899: Last Check
900-999: Remount all TARGET FS in /mnt/local + post-recovery (NBU)
```

**Comment by jsmeix** [comment]
@schabrolles 
I assume it works for you on your PPC tests systems?

@gdha 
could you also have one more look here if it looks o.k.
so that it can be merged?

**Comment by schabrolles** [comment]
@jsmeix Yes, tested on rhel6, rhel7, sles11, sle12 on POWER

**Comment by jsmeix** [comment]
When there are no objections, I will merge it soon.

**Pull request merged**
