### PR TITLE
fix non ASCII characters in documentation

### PR DESCRIPTION
**Pull request by jsmeix**
first steps to fix non ASCII characters in rear-release-notes.txt
reated to issue 1018

### CODE REVIEW

**Comment by jsmeix** [comment]
do not yet merge it - it is currently work-in-progress...

**Comment by jsmeix** [comment]
@gdha 
I fixed non-ASCII characters in doc/rear-release-notes.txt
and I would like that you have a look.

If it is o.k. for you I think it should be merged soon
so that you could further work on doc/rear-release-notes.txt
for the 1.19 release.

**Comment by gdha** [comment]
@jsmeix Be aware that **release-notes.txt** is pulled from the web (via w3m - see https://github.com/rear/rear/wiki/Release-process) - I never edit this file directly. If there are non-ASCII charecters then we should fix this in https://github.com/rear/rear.github.com/blob/master/documentation/release-notes-1-19.md

**Comment by jsmeix** [comment]
Damn!
I did all my changes in vain :-(

**Comment by jsmeix** [comment]
Got one step further:

According to https://github.com/rear/rear/wiki/Release-process
only
<pre>
w3m -dump -cols 78 http://relax-and-recover.org/documentation/release-notes-1-19 >rear-release-notes.txt
</pre>
is insufficient and you can get arbitrary encoding in the w3m output
depending on your current locale ettings and on undocumented
black magic in w3m.
E.g. for me:
<pre>
export LC_ALL=POSIX
export LANG=POSIX

w3m -dump -cols 78 http://relax-and-recover.org/documentation/release-notes-1-19 >rear-release-notes.txt

file rear-release-notes.txt
rear-release-notes.txt: UTF-8 Unicode English text
</pre>

One needs to actively convert the w3m output into the
desired encoding:
<pre>
export LC_ALL=POSIX
export LANG=POSIX

w3m -dump -cols 78 http://relax-and-recover.org/documentation/release-notes-1-19 | iconv -f UTF-8 -t ASCII//TRANSLIT -o rear-release-notes.txt

file rear-release-notes.txt
rear-release-notes.txt: ASCII English text
</pre>

But now one gets in rear-release-notes.txt things like
<pre>
  o Integrates with internal backup solutions such as:

      ? GNU tar (BACKUP=NETFS, BACKUP_PROG=tar)
 </pre>
so that one additionally has to replace the '?' mark
with a reasonable ASCI character e.g.:
<pre>
w3m -dump -cols 78 http://relax-and-recover.org/documentation/release-notes-1-19 | iconv -f UTF-8 -t ASCII//TRANSLIT | sed -e 's/^      ? /      - /' >rear-release-notes.txt
</pre>

**Pull request closed without merging**
