### PR TITLE
Test actions

### PR DESCRIPTION
**Pull request by antonvoznia**
#### Relax-and-Recover (ReaR) Pull Request Template

Please fill in the following items before submitting a new pull request:

##### Pull Request Details:

* Type: **Bug Fix** / **New Feature** / **Enhancement** / **Other?**

* Impact: **Low** / **Normal** / **High** / **Critical** / **Urgent**

* Reference to related issue (URL):

* How was this pull request tested?

* Brief description of the changes in this pull request:

### CODE REVIEW

**Comment by pcahyna** [comment]
Hello Anton,

can you please open test/experiment PRs against your own fork, or my fork, to avoid noise for other ReaR developers (unless you want them to see the changes)?

@rear/contributors : Anton is my student, working on CI for ReaR. (I already had a student for the same topic two years ago, as you might recall, but he dropped out.) I can present the subject on the mailing list.

**Comment by jsmeix** [comment]
@pcahyna 
thank you for your explanation about
this pull request without any word of reasoning about "what" and "why" in
https://github.com/rear/rear/blob/master/.github/PULL_REQUEST_TEMPLATE.md

I would prefer a matching issue here at GitHub about `CI for ReaR`
because I prefer GitHub's issue features over plain e-mail communication.
Of course additionally there can be an e-mail if you like.

**Comment by antonvoznia** [comment]
Hello,
I'm so sorry, it was my mistake. Of course, I've done it accidentally.

Thanks,
Anton

**Comment by jsmeix** [comment]
@antonvoznia 
no problem - @pcahyna explained it all.
Mistakes just happen - and this one was a really tiny one without any bad effect.

**Pull request closed without merging**
