### PR TITLE
Use mpathconf to setup multipath in recovery (if available) 

### PR DESCRIPTION
**Pull request by schabrolles**
mpathconf is present in Fedora based distribution. It helps to make the first configuration of multipath.
It can be used to properly setup the multipath configuration during recovery when you migration from non-multipath system to multipath. (see #1311, #1314)

Having a good `multipath.conf` since the very beginning (start of recovery) is important because this file can determine the name of the multipath device.

with an empty multipath.conf : `/dev/mapper/3600507680c82004cf8000000000000d8`
with a multipath.conf with friendly name (setup with mpathconf) : `/dev/mapper/mpatha`

The issue is : 
During migration, the recovery process will use THIS name to modify some key file on the target OS.
(lilo.conf, yaboot.conf etc ...). It is why it is important to get the good name from the beginning.

This patch propose to 
 - add `mpathconf` tool in the recovery image if it exists.
 - use `mpathconf` (if available) to properly setup the multipath during device discovery.

### CODE REVIEW

**Comment by jsmeix** [comment]
@schabrolles 
does the
<pre>
# load mudules and start multipath discovery
</pre>
comment also need to be moved outside the if statement?

**Comment by schabrolles** [comment]
@gdha, @jsmeix  I've updated with your comments ...

**Comment by schabrolles** [comment]
@gdha , @jsmeix  I finally find a way to use friendly_names with SUSE by forcing the binding file location in `multipath.conf`.

tested on sles11, sles12, rhel6 and rhel7

**Comment by jsmeix** [comment]
When there are no objections
I will merge it soon...

**Pull request merged**
