### PR TITLE
Exit if TSM_RESULT_SAVE is false or PXE_TFTP_URL is defined.

### LINKED ISSUE #1342: Error: "No files to copy (RESULT_FILES is empty)" when using TSM + PXE
During mkrescue phase I got the error : 
`Error: "No files to copy (RESULT_FILES is empty)"`

`output/TSM/default/950_dsmc_save_result_files.sh` try to backup `RESULT_FILES`, bit those one seems to be removed by previous script : `output/TSM/default/800_copy_tftp.sh`

=> `$RESULT_FILES` is empty, then we got the error message.

`950_dsmc_save_result_files.sh` should not run if ` $PXE_TFTP_URL` is set 

#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): 2.00-git
* OS version (cat /etc/rear/os.conf or lsb_release -a): SLES 11 SP4
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Are you using legacy BIOS or UEFI boot?
* Brief description of the issue:
* Work-around, if any:

Extract from /etc/rear/local.conf
```
AUTOEXCLUDE_MULTIPATH=n
BOOT_OVER_SAN=y

COPY_AS_IS_TSM=( /etc/adsm/TSM.PWD /opt/tivoli/tsm/client/ba/bin/dsmc /opt/tivoli/tsm/client/ba/bin/tsmbench_inclexcl /opt/tivoli/tsm/client/ba/bin/dsm.sys /opt/tivoli/tsm/client/ba/bin/dsm.opt /opt/tivoli/tsm/client/api/bin64/libgpfs.so /opt/tivoli/tsm/client/api/bin64/libdmapi.so /opt/tivoli/tsm/client/ba/bin/EN_US/dsmclientV3.cat /usr/local/ibm/gsk8* )

OUTPUT=PXE
OUTPUT_PREFIX_PXE=rear/$HOSTNAME

PXE_CONFIG_GRUB_STYLE=y
# On your TFTP server:
# In your tftpboot dir execute the following command to create the netboot directory based on GRUB.
# grub2-mknetdir --net-directory=/var/lib/tftpboot
# config directory will be /var/lib/tftpboot/boot/grub2/powerpc-ieee1275
# More information about setting up a PXE based on Grub on POWER : https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/chap-installation-server-setup.html#sect-network-boot-setup-ppc-grub2
PXE_TFTP_IP=10.7.19.177
PXE_CONFIG_URL="nfs://$PXE_TFTP_IP/var/lib/tftpboot/boot/grub2/powerpc-ieee1275"
PXE_CREATE_LINKS=IP
PXE_REMOVE_OLD_LINKS=y
PXE_TFTP_URL="nfs://$PXE_TFTP_IP/var/lib/tftpboot"

USE_STATIC_NETWORKING=y

BACKUP=TSM
TSM_RESULT_SAVE=n

REAR_INITRD_COMPRESSION=lzma
```

### PR DESCRIPTION
**Pull request by schabrolles**
Should fix #1342
 - No need to copy files if `TSM_RESULT_SAVE` is false
 - When `$PXE_TFTP_URL` is defined, results files are deleted by
 `800_copy_to_tftp.sh` ... So it produce an Error "No files to copy (RESULT_FILES is empty)"

### CODE REVIEW

**Comment by jsmeix** [comment]
Regarding clean up of
<pre>
if [[ "$TSM_RESULT_SAVE" = "n" ]]; then
</pre>
in 950_dsmc_save_result_files.sh
I wonder what the actual meaning of that condition is?
Strictly reading the code  it is
<pre>
if is_false $TSM_RESULT_SAVE ; then
</pre>
but actually the meaning could be
<pre>
if ! is_true $TSM_RESULT_SAVE ; then
</pre>
it depends on what the fallback behaviour should be
for TSM_RESULT_SAVE.

@schabrolles 
as it seems you work with TSM, it is your decision
what fallback behaviour should be in ReaR
in case of BACKUP=TSM

In general regarding TSM support in ReaR
you may also have a look at
https://github.com/rear/rear/issues/823

**Comment by jsmeix** [comment]
@schabrolles 
if it is o.k. from your side I would "just merge" it.

**Comment by schabrolles** [comment]
Looks good to me, I agree with your last message, but the default setting is TSM_RESULT_SAVE=y and I think it is better if skip the RESULT_SAVE when the user explicitly ask to NOT save it ...

**Comment by gdha** [comment]
@schabrolles @jsmeix See also issues #634 and #734 for the discussions in there. Might be wishful thinking?

**Comment by jsmeix** [comment]
@gdha 
thanks to mention that OUTPUT_URL=null
is a related topic.
I don't think it is wishful thinking.
But I think in general support for third party tools
(in particular third party backup software)
needs sponsorship because third party tool issues
can only be implemented by someone who actually
uses and tests ReaR with a particular third party tool.
As long as the support for third party tools
is considered "sufficient" by its users
it is o.k. as is ;-)

**Pull request merged**
