### PR TITLE
Replace pstree by ps command (issue#1755)

### PR DESCRIPTION
**Pull request by jsmeix**
* Type: **Bug Fix**

* Impact: **Low**

* Reference to related issue (URL):
https://github.com/rear/rear/issues/1755

* How was this pull request tested?
On my SLES11 and SLES12 systems.

* Brief description of the changes in this pull request:
Show descendant processes PIDs with their commands in the log
so that later the plain PIDs in the log get more comprehensible.
What works sufficiently on all systems is "pstree -Aplau $MASTER_PID"
but the pstree command is not available in the ReaR recovery system
so that the ps command is used as fallback.

### CODE REVIEW

**Comment by jsmeix** [comment]
No longer a real "cleanup" because with what I ended after
lots of trial and error on SLES10 SLES11 and SLES12 is
<pre>
Log "$( pstree -Aplau $MASTER_PID || ps f -g $MASTER_PID -o pid,args || ps --ppid $MASTER_PID -o pid,args )"
</pre>
because currently I don't know a 'ps' command that "just works" on
SLES10 SLES11 and SLES12 to show all descendant processes.
For details see my comments in the code.

**Comment by gdha** [comment]
@jsmeix code looks good and works on centos. Just one remark if I may? Shouldn't we add `pstree` to the PROGS array?

**Comment by jsmeix** [comment]
@gdha 
if you don't mind I would like to have pstree by default in the recovery system
because personally I am much used to use it regularily and missed it already
several times in the past in the recovery system.

**Comment by jsmeix** [comment]
Adding pstree to PROGS inceases the recovery system size
by basically only the size of the /usr/bin/pstree binary
(which is on my SLES11 system about 23 KiB)
because /usr/bin/pstree needs only standard libraries.

**Comment by LaurianoElmiroDuarte** [comment]
summarizing the process just changed its name, from pstree to psmisc

**Pull request merged**
