### PR TITLE
Obey TSM_RESTORE_PIT_... variables in environment (issue 1948)

### PR DESCRIPTION
**Pull request by jsmeix**
* Type: **Enhancement**

* Impact: **Normal**

* Reference to related issue (URL):
https://github.com/rear/rear/issues/1948

* How was this pull request tested?
Not at all tested by me because I do not use TSM

* Brief description of the changes in this pull request:
A blind attempt by plain looking at the code
which is intended as a proposal how I think
https://github.com/rear/rear/issues/1948
might be implemented.

### CODE REVIEW

**Comment by jsmeix** [comment]
@schabrolles 
I noticed inconsistencies about th date format
for TSM Point-In-Time Restore in what was written in the comments
in default.conf
<pre>
internally MM/DD/YYYY is used
</pre>
and in verify/TSM/default/390_request_point_in_time_restore_parameters.sh
<pre>
LogPrint "Restoring all filespaces from backup before ... (MM/DD/YYYY HH:mm:ss)"
</pre>
versus what the code
in verify/TSM/default/390_request_point_in_time_restore_parameters.sh
actually does
<pre>
TSM_RESTORE_PIT_DATE=$( date -d "$REPLY" +%Y.%m.%d 2>/dev/null ) ...
</pre>

Furthermore is seems the dsmc option `-date=5` is set twice first in
<pre>
TSM_DSMC_RESTORE_OPTIONS=( "${TSM_DSMC_RESTORE_OPTIONS[@]}" -date=5 -pitd="$TSM_RESTORE_PIT_DATE" )
</pre>
and then again in
<pre>
TSM_DSMC_RESTORE_OPTIONS=( "${TSM_DSMC_RESTORE_OPTIONS[@]}" -date=5 -pitt="$TSM_RESTORE_PIT_TIME" )
</pre>
Perhaps it is really needed two times or perhaps it does not matter?

**Comment by jsmeix** [comment]
Ok ok I better leave here.

FWIW:
I think the usual way are pull requests (at least all others seem to do it this way)?

**Comment by schlomo** [comment]
Yes, PR is great.  That's why I put my code into an issue branch here in our common repo so that everybody in our team can work on it or suggest changes. I was just surprised why you made a PR to master and not to the issue repo.

**Comment by jsmeix** [comment]
I had missed this comment
https://github.com/rear/rear/issues/1948#ref-commit-f5558ef

**Pull request closed without merging**
