### PR TITLE
Correction in behavior of Borg environment variables

### PR DESCRIPTION
**Pull request by gozora**
Applied changes discussed in #1052.

### CODE REVIEW

**Comment by jsmeix** [comment]
@gozora 
if this pull request is finished from your point of view
I woulkd just merge it.

**Comment by gozora** [comment]
@jsmeix Yes, it is.

**Comment by jsmeix** [comment]
I found a typo in a comment in default.conf:
<pre>
into ReaRs local.conf/site.conf.
</pre>
(i.e. the plural ...s is used here)
should be
<pre>
into ReaR's local.conf/site.conf.
</pre>
(i.e. the genitive ...'s is actually meant)

No need to do a pull request only because of this.
Perhaps you can include it in a future pull request.

**Comment by gozora** [comment]
@jsmeix I'll correct it, just give me a minute ;-)

**Comment by gozora** [comment]
ah you've merged it already ...
So fine, I'll note it somewhere ...

**Comment by jsmeix** [comment]
I found another minor issue in default.conf:

On my system I get:
<pre>
$ less usr/share/rear/conf/default.conf
...
# When set, use the given path/filename as remote path (default is â200234borgâ200235)
...

$ file usr/share/rear/conf/default.conf
usr/share/rear/conf/default.conf: UTF-8 Unicode English text
</pre>

You use UTF-8 characters.
Please use only simple traditional (7-bit) ASCII charactes, cf.
https://github.com/rear/rear/issues/1018#issuecomment-251385721

**Comment by jsmeix** [comment]
I added a section "Character Encoding" to
https://github.com/rear/rear/wiki/Coding-Style

**Comment by gozora** [comment]
That was an accident. Since my grammar fiasco. I use Libreoffice for spellchecks ...

**Comment by jsmeix** [comment]
Ahhh!
You trust robots (LibreOffice) more than yourself ;-))

**Comment by gozora** [comment]
Of course I do! :-)

**Comment by gozora** [comment]
`apt-get install geany-plugin-spellcheck` (hopefully) did the trick. Now I can look smart and use right encoding as well :-)

**Comment by jsmeix** [comment]
Right now I remember that I can simply fix such minor typos
directly via the GitHub web frontend which I did hereby:
https://github.com/rear/rear/commit/6ccbab0839d25b8d7291741f380b308970371999

**Comment by gozora** [comment]
Thanks!

**Pull request merged**
