### PR TITLE
Add automatically some important kernel parameters to KERNEL_CMDLINE

### PR DESCRIPTION
**Pull request by schabrolles**
I propose to check the current kernel parameters used (in `/proc/cmdline`) to detect some important parameter we should use when booting in rescue mode (means  add them in KERNEL_CMDLINE variable).

Based on the discussion with @gdha in #1400, I started to detect `net.ifnames` or `biosdevname` parameter in order to preserve interface naming between rescue mode and real system after migration.

### CODE REVIEW

**Comment by schabrolles** [comment]
@gdha It was my thought.... I was starting this scipt by considering KERNEL_CMDLINE was an array ... but it was not ;-) May be @jsmeix or @schlomo  could tell us why it is a variable and not an array.

@jsmeix, I've just made some adjustments (using a Array CHECK_KERNEL_PARAMETER in default.conf). Does it fit your expectation ? (not sure I understand what you mean by "implement it via
generically working code ")

**Comment by jsmeix** [comment]
FWIW:
Bash arrays are in the end only needed when the elements
could be strings (i.e. consist of several words) so that
<pre>
# strings=( first 'second thing' last )

# for string in "${strings[@]}" ; do echo "'$string'" ; done
'first'
'second thing'
'last'
</pre>
works.
When things are only words, a simple string is sufficient
because then simple
<pre>
# words=" first second third"

# for word in $words ; do echo "'$word'" ; done
'first'
'second'
'third'
</pre>
already works.
Careful note quoting versus non-quoting!

**Comment by schabrolles** [comment]
@jsmeix variable name changed. 

I'm waiting for last feedback/approval from @gdha and @schlomo  before merging this one.

**Comment by schlomo** [comment]
Looks good to me. Did you check it with kernel options that are bare words without a `=`? Like `gpt`?

**Comment by schabrolles** [comment]
@schlomo, Yes it also works with parameters without `=` like `quiet` (just tested)

**Comment by schlomo** [comment]
Thanks, go ahead and merge.

**Pull request merged**
