### PR TITLE
let each ldd output line match only once

### PR DESCRIPTION
**Pull request by jgrumboe**
#### Relax-and-Recover (ReaR) Pull Request Template

Please fill in the following items before submitting a new pull request:

##### Pull Request Details:

* Type: **Bug Fix** / **New Feature** / **Enhancement** / **Other?**
Bug Fix

* Impact: **Low** / **Normal** / **High** / **Critical** / **Urgent**
Normal

* Reference to related issue (URL):
https://github.com/rear/rear/issues/2109

* How was this pull request tested?
locally on my system

* Brief description of the changes in this pull request:
This change lets ldd output lines match only once in the awk statement.
So it prohibits "wrong" double matches.

### CODE REVIEW

**Comment by rmetrich** [comment]
Looks ok to me. Any example of why it would be wrong to print multiple lines?

**Comment by jgrumboe** [comment]
@rmetrich The "problem" is that in this case with Dynatrace the loaded library has "/$LIB/" in the name and, as far as i know, the actual full-path of the lib is evaluated during runtime of the process.
As described in the referenced issue #2109 it gives stderr messages, which somehow are false-positive.
In the Dynatrace example the /lib64/liboneagentproc.so is already loaded so "/$LIB/liboneagentproc.so" is not needed anymore.

I hope my answer makes sense and i didn't mix it up to much while translating my thoughts into english ;)

**Comment by jgrumboe** [comment]
Regarding my issue comment (https://github.com/rear/rear/issues/2109#issuecomment-480815587) this PR would be obsolet or let's say "cosmetic", if you still want to merge it.
Thanks for pointing me to #1980.

**Comment by jsmeix** [comment]
@rmetrich 
since https://github.com/rear/rear/pull/2110#issuecomment-480816157
my gut feeling tells me it would be better to not merge it,
I guess my gut feeling is "never change code that works".

**Comment by jsmeix** [comment]
FYI: I found out how one can un-approve a pull request:
It does not work to do another review where one selects only "comment"
but it works to re-request oneself to do a review.

**Comment by jsmeix** [comment]
@rmetrich 
I assigned it to you so that you can decide whether or not to merge it.

**Comment by jgrumboe** [comment]
I'll be happy if you merge it, but i would also understand when this is rejected because of "never change code that works" - no problem for me. :)

**Comment by gdha** [comment]
@rmetrich What do you think about this PR - accept or reject?

**Comment by rmetrich** [comment]
I'm ok as long as it still works. Could a test be made with NBU?

Renaud.

Out of the office / Sent from my phone.

**Comment by gdha** [comment]
@jgrumboe I assume you were hitting this issue when using TSM as external backup solution?

**Comment by jgrumboe** [comment]
@gdha "Maybe". Yes, we do have TSM as external backup solution and No, i don't think it's TSM related. The function to scan loaded libs is general I think.

**Comment by jsmeix** [comment]
Not urgent or "must have" for ReaR 2.5 so postponed to ReaR 2.6

**Comment by gdha** [comment]
@rmetrich It is up to you to decide to merge this PR or not. I have no preference in this case.

**Comment by gdha** [comment]
@rmetrich @jsmeix If this PR is not merged before end of November 2019 I will close it without further notice (say not merging the changes). Agree?

**Comment by jsmeix** [comment]
@gdha 
I agree with your https://github.com/rear/rear/pull/2110#issuecomment-551436506

**Comment by jsmeix** [comment]
Because this pull request has merge conflicts since
https://github.com/rear/rear/commit/c3886c81e5be26e390ce907b640875ded7748714
and because of
https://github.com/rear/rear/pull/2110#issuecomment-551436506
I close it.

**Pull request closed without merging**
