### PR TITLE
First partially working implementation of the new ZYPPER backup method 

### PR DESCRIPTION
**Pull request by jsmeix**
See
https://github.com/rear/rear/issues/1085

For me BACKUP=ZYPPER works in a very initial basic way
on my SLES12 test system with only one system partition
with ext4 (and one swap partition) with this local.conf:
<pre>
OUTPUT=ISO
BACKUP=ZYPPER
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://10.160.4.244/nfs
SSH_ROOT_PASSWORD="rear"
USE_DHCLIENT="yes"
</pre>

Currently the new created system boots
and the login screen shows up but
currently one cannot log in because
no root pasword is set which is the
next thing I will implement.

Nevertheless the current state looks so promising to me
that I like to merge it into the ReaR master code because
I think I can make it work sufficiently well.

If there are no objections I like to merge it on Monday.

### CODE REVIEW

**Comment by gdha** [comment]
@jsmeix no problem for me - I trust you enough ;-)
However, could you explain in a one-liner what makes **BACKUP=ZYPPER** so different from e.g. **BACKUP=NETFS** ?

**Comment by jsmeix** [comment]
I can explain but never ever in a one-liner
except this one-line is sufficient for you:
<pre>
BACKUP=ZYPPER is totally different compared to e.g. BACKUP=NETFS
</pre>
;-)

Seriously:
When BACKUP=ZYPPER works sufficiently well
I will make explanatory documentation, same way
as I did for the "multiple backup methods".

For today:
Have a nice weekend!

**Comment by jsmeix** [comment]
Meanwhile for me BACKUP=ZYPPER works in a basic way
on my SLES12 test system with only one system partition
with ext4 (and one swap partition) with this local.conf:
<pre>
OUTPUT=ISO
BACKUP=ZYPPER
ZYPPER_REPOSITORIES=( "cd:///?devices=/dev/disk/by-label/SLE-12-SP2-Server-DVD-x86_642192" )
ZYPPER_INSTALL_RPMS="independent_RPMs"
ZYPPER_ROOT_PASSWORD=""
ZYPPER_NETWORK_SETUP_COMMANDS=( 'YAST' 'systemctl enable sshd.service' )
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://10.160.4.244/nfs
SSH_ROOT_PASSWORD="rear"
USE_DHCLIENT="yes"
</pre>

Currently there are lots of rough edges so that BACKUP=ZYPPER
will not yet be officially announced but for interested users
with a SUSE system (preferably SLES12 what I use)
the ZYPPER_* variables are described in default.conf.

**Comment by jsmeix** [comment]
@gdha 
over the weekend I even found an almost-one-liner for you:
<pre>
BACKUP=ZYPPER results a pristine "raw" system
(with default config files from the RPM packages)
that must be configured as needed.
</pre>
cf.
"Generic system installation with the plain SUSE installation system"
in
https://en.opensuse.org/SDB:Disaster_Recovery

**Pull request merged**
