### PR TITLE
Fix 2360: Apply xxx_fix_broken_links.sh before files get modified in recovery system

### PR DESCRIPTION
**Pull request by OliverO2**
##### Pull Request Details:

* Type: **Bug Fix**

* Impact: **Normal**

* Reference to related issue (URL): #2360

* How was this pull request tested? On Ubuntu 18.04.4 LTS

* Brief description of the changes in this pull request: See issue.

### CODE REVIEW

**Comment by jsmeix** [comment]
@OliverO2 
thank you!
I will have a look...

**Comment by OliverO2** [comment]
Thanks, take your time. I'm just preparing another issue and PR concerning `sshd_config`.

**Comment by jsmeix** [comment]
@rear/contributors 
when there are no objections I would like to merge it today afternoon.

**Comment by gdha** [comment]
@jsmeix no problems - just do it

**Pull request merged**
