### PR TITLE
Added confidential mode '-C' for UserInput

### PR DESCRIPTION
**Pull request by jsmeix**
In confidential mode (via '-C') the UserInput function
does to not log possibly confidentia data which means
neither the actual user input nor the default input
nor the choices values are logged.
The confidential UserInput mode is in particular
intended to be used in
https://github.com/rear/rear/pull/1500

### CODE REVIEW

**Comment by jsmeix** [comment]
I "just merge " it now so that @OliverO2 can try it out
whether or not it works in its current form for his
https://github.com/rear/rear/pull/1500

**Comment by jsmeix** [comment]
@OliverO2 
please provide feedback whether or not the current
confidential user input mode is as you need it.
I can further enhance it as you need.

**Comment by jsmeix** [comment]
Of course in ReaR debugscripts mode
(via 'rear -D' that runs all scripts with 'set -x')
arbitrary - also possibly conffential stuff - gets logged.
If this is not acceptable I could further enhance the
confidential user input mode to switch off 'set -x'
during the UserInput call and re-enable it afterwards.

**Comment by schlomo** [comment]
I am against hinding passwords in debug mode. Users won't use that in production and it will help us to understand bugs. Adding extra obfuscation here will only add complexity and be a nice source for bugs that are hard to catch.

**Pull request merged**
