### PR TITLE
Corrected bug reported in issue #866

### PR DESCRIPTION
**Pull request by gozora**

### CODE REVIEW

**Comment by jsmeix** [comment]
@gozora 
your comment in lib/bootloader-functions.sh about
"SLES12 SP1 boot throw kernel panic without root= set"
shows that you have tested it at least on SLES12 SP1
which is sufficient for me to just merge it so that @abbbi
can easily test if now https://github.com/rear/rear/issues/866
works for him.

**Comment by gozora** [comment]
@jsmeix Yes, correct.
My UEFI test vector currently consists from testing on SLES12 SP1, Debian and Centos.

**Comment by jsmeix** [comment]
@gozora 
and once more many thanks for your
valuable contribution to Relax-and-Recover!

**Comment by gozora** [comment]
no problem ;-)

**Pull request merged**
