### PR TITLE
Renumbering (NM becomes NM0) to get more free number space

### PR DESCRIPTION
**Pull request by jsmeix**
Get more free number space in particular for user scripts, cf.
https://github.com/rear/rear/pull/1051#issuecomment-256581232

Renumbered by ading a trailing 0 so that 12 becomes 120
except 00 which becomes 005 and adapted symlinks
to point again to the right re-numbered scripts.
Cf. https://github.com/rear/rear/pull/1051

### CODE REVIEW

**Comment by jsmeix** [comment]
Do not yet merge it.

I need to test it and I like to adapt all texts where
the old script names are used to the new numbering:
"NM_foo_bar.sh" -> "NM0_foo_bar.sh"
"00_blah.sh" -> "005_blah.sh"

**Comment by jsmeix** [comment]
Now the sequence of scripts is even more messed up compared to https://github.com/rear/rear/pull/1051#issuecomment-256338122

Since there are now three digits used (instead of two)
I also need to fix the way how the sequence of scripts
is generated...

Incredible how fragile all that is...

Impressive that it works at all ...

**Comment by jsmeix** [comment]
I verified that the sequence of scripts is the same
before and after renumbering for "rear mkbackup -s"
and "rear recover -s" with BACKUP=NETFS.

I tested "rear mkbackup" and "rear recover"
with BACKUP=NETFS on my SLES12-SP2 system
and it still works for me.

Because I changed all scripts (all got at least a new number)
I will merge it now to avoid conflicts with further work.

**Comment by schlomo** [comment]
Brilliant idea, thanks a lot!

Am 27.10.2016 12:48 nachm. schrieb "Johannes Meixner" <
notifications@github.com>:

**Comment by jsmeix** [comment]
@schlomo 
very many thanks for your positive feedback!

I was in fear my re-numbering causes more
pain and annoyance than it is actually worth.

But I also think we really needed more free space
in the numbering to be future-proof for some time.

**Comment by schlomo** [comment]
We should just make it very clear in the release notes that existing custom
scripts need to be adapted to the new numbering scheme.

Since this is somewhat a breaking change maybe it is worth bumping the
major version number, too? Or at least abort with an error if NN_*.sh files
are found?

I think increasing the major version number on a regular base would also
signal more development happening :-)

**Comment by jsmeix** [comment]
@schlomo 
I like the general idea of a major version bump.

@gdha 
what do you think about using FOSDEM to introduce
a new Relax-and-Recover major version?

According to the "Milestone" dates here "Rear v1.20" is
planned end of December 2016.

Perhaps it is better to skip that and have a
"Relax-and-Recover v 2.0" at FOSDEM 2017
(e.g. end of January just before FOSDEM)?

**Comment by jsmeix** [comment]
I will implement an error if NN_*.sh files are found.

I may try to implement an error if files starting with digits
are found that do not match the NNN_ scheme.

**Comment by schlomo** [comment]
Since people are usually wary of a X.0 version I would suggest to do the
2.0 release sooner and then have a 2.1 or 2.2 ready for FOSDEM :-)

**Pull request merged**
