### PR TITLE
Add missing but required NFS users for proper rpcbind startup

### PR DESCRIPTION
**Pull request by hpannenb**
* Type: **Bug Fix** / **New Feature** / **Enhancement** / **Other?**
**Bug Fix**
* Impact: **Low** / **Normal** / **High** / **Critical** / **Urgent**
**Low**
* Reference to related issue (URL):
#2341 and #2250 
* How was this pull request tested?
- Under RHEL7.6: On a  HPE DL360 Gen10.
- Under Debian 10: -

* Brief description of the changes in this pull request:
This pull request adds the missing but required NFS users for RHEL7.x and Debian 10 to let `rpcbind `start successfully during recovery.

### CODE REVIEW

**Comment by hpannenb** [comment]
Maybe there is/will be a more sophisticated approach to determine the required users "automagically".
This would be benefitial because i.e. on Ubuntu 18.04.4 I see the `rpcbind `runs under `root`.

**Comment by jsmeix** [comment]
Now I found why using `ARRAY+=( additional elements )`
lets array things work more fail-safe, see
the initial description of @pcahyna in
https://github.com/rear/rear/issues/2220
where he wrote (excerpt):
```
In the present case, a less invasive change would be
to replace the appending to the array

   CLONE_USERS=( "${CLONE_USERS[@]:-}" daemon rpc usbmuxd usbmux vcsa nobody dbus )

by '+=', i.e.

   CLONE_USERS+=( daemon rpc usbmuxd usbmux vcsa nobody dbus )

(I've verified that '+=' works properly
 even in bash 3 and 'set -ue'.)
This would fix the present case and other cases
where the problem lies in appending to arrays,
but not those where the array is already initialized to ("").
```

**Comment by jsmeix** [comment]
@rmetrich 
if there are no objectiond from you
I would like to merge it today afternoon.

**Comment by pcahyna** [comment]
@hpannenb :+1: to the replacement of array operations by `+=`, even if this is not the main point of the PR. See #2220 , #2223

**Comment by pcahyna** [comment]
> Maybe there is/will be a more sophisticated approach to determine the required users "automagically".
> This would be benefitial because i.e. on Ubuntu 18.04.4 I see the `rpcbind `runs under `root` which will not lead to such an issue there.

Yes it is a bit unfortunate that we must hard-code such special knowledge.

**Comment by jsmeix** [comment]
@pcahyna 
see https://github.com/rear/rear/issues/2345
for a possible solution that would be simple and generic
without endless mainenance of hard-coded special knowledge.

**Pull request merged**
