### PR TITLE
btrfs subvolumes generic: fix 'subvolume set-default' for older versions

### PR DESCRIPTION
**Pull request by OliverO2**
##### Pull Request Details:

* Type: **Bug Fix**

* Impact: **Normal**

* Reference to related issue (URL): https://github.com/rear/rear/pull/2080#issuecomment-472448686

* How was this pull request tested? On Ubuntu 16.04 and 18.04

### CODE REVIEW

**Comment by OliverO2** [comment]
@jsmeix Hopefully, this fix makes the generic code work on SLES12 now - and on the entire universe ;-).

**Comment by jsmeix** [comment]
Not urgent or "must have" for ReaR 2.5 so postponed to ReaR 2.6

**Comment by OliverO2** [comment]
I'd like you to reconsider including this PR into ReaR 2.5, too, for these reasons:
1. The entire script `135_include_btrfs_subvolumes_generic_code.sh` is not enabled by default, but depends on the yet undocumented variable `BTRFS_SUBVOLUME_GENERIC_SETUP`.
1. It is a tiny change, which has been successfully tested in several mkrescue/recover cycles while checking that a default subvolume (and thus the changed code) was actually used.
1. If people want to try the new code in its packaged form, they should have a positive experience on  first use, even on older OS versions.

Of course, after releasing ReaR 2.5, the entire code should still be tested on a wider range of systems (including the ancient ones). The design goal remains to have just one copy of btrfs subvolume handling code.

**Comment by jsmeix** [comment]
@OliverO2 
of course I agree with your
https://github.com/rear/rear/pull/2119#issuecomment-488288078

I only liked to test it also on SLES out of curiosity
but found no time yet...

Because SLES uses totally separated different code
this changes cannot cause regressions on SLES
so that I can "blindly approve" them for SLES.

@gdha 
should we have that in ReaR 2.5?
From my current selfish SLES-only point of view I would say yes.

**Comment by gdha** [comment]
@jsmeix release 2.5 is fine for me.

**Comment by OliverO2** [comment]
Thanks to both of you!

@jsmeix https://github.com/rear/rear/pull/2119#issuecomment-488593331

> I only liked to test it also on SLES out of curiosity
> but found no time yet...

Sure, and I also understand that you'd like to get the release done. Would you like me to add an issue for the integration testing so that there some  reminder after this PR is merged?

**Pull request merged**
